add the function to edit register value
eclipse-cdt-cloud/cdt-gdb-adapter pull request #199
Opened 2022-08-15 11:06 UTC by QuocDoBV

2022-08-15 11:22 UTC, jonahgraham commented
Hi @QuocDoBV thanks for they PR. Unfortunately it looks like this version has some problems as the change is in the wrong file making the diff very large. Also the ECA check fails. Perhaps @quyettrinhrvc can advise on how to resolve ECA issue.

2022-08-15 11:26 UTC, QuocDoBV commented
Hi @jonahgraham thanks a lots for your information.

2022-08-16 03:43 UTC, QuocDoBV commented
Hi @jonahgraham,
After @quyettrinhrvc support, ECA issue has been resolved. 
Currently, we can only  edit local value on Variable view. When we edit register value, Some errors will display. So, I have changed code to edit register value can work.  
Could you please review it help me?
Thank a lot.

2022-08-16 12:23 UTC, jonahgraham commented
Hi, this looks good - we need some tests. @quyettrinhrvc wrote the register read tests here: https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/blob/7ef1e9204dc750d77848e870595ea992a202d28d/src/integration-tests/var.spec.ts#L127-L129

The equivalent for setting variables is a little further down the file: https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/blob/7ef1e9204dc750d77848e870595ea992a202d28d/src/integration-tests/var.spec.ts#L189-L199

2022-08-18 01:13 UTC, QuocDoBV commented
Hi @jonahgraham,
Sorry for my reply late. 
I have tried to run integration tests which cloned from https://github.com/quyettrinhrvc/cdt-gdb-adapter to make sure that I have a correct environment. And, the result is that all tests are passed. You can check the result here [integration.zip](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/files/9366782/integration.zip).  However, when I run integration tests in latest version  from https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter (There are some tests added to check for multiple threads), some problems occur with tests with tests that involve multiple threads . You can check the problem at[integration.zip](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/files/9366794/integration.zip). And, when I run the tests from https://github.com/QuocDoBV/cdt-gdb-adapter(my pull request) there are some problems like when running with cdt-gdb-adapter latest version . You can check the result here [integration.zip](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/files/9366822/integration.zip). So I thinks that the problem when I run integration tests from my pull request is not related to my changes. 
Could you please help me check and confirm it?
Could you tell me that do I need to add more integration tests or just run the current integration tests and confirm it? 
 If yes, could you please give me some advices? I'm new here. So sorry I don't have much experience in this.
Thanks a lot.

2022-08-21 21:23 UTC, jonahgraham commented
I don't see any failures in the integration.zip file you attached. I do see skipped tests, which is expected, some tests cannot be run on every machine. Rather than attach the machine readable xml file, you can provide the failed tests from the stdout, e.g. like this:

```
  Suite duration: 0.394 s, Tests: 1

  0 passing (405ms)
  1 failing

  1) stop
       handles segv:

      AssertionError: expected 'SIGSEGV' to equal 'SI2GSEGV'
      + expected - actual

      -SIGSEGV
      +SI2GSEGV
      
      at /scratch/debug/git/cdt-gdb-adapter/dist/integration-tests/stop.spec.js:33:57
      at Generator.next (<anonymous>)
      at fulfilled (dist/integration-tests/stop.spec.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

> Could you tell me that do I need to add more integration tests or just run the current integration tests and confirm it?

You need new tests to cover your new functionality.

2022-08-21 21:24 UTC, jonahgraham commented
> If yes, could you please give me some advices? I'm new here. So sorry I don't have much experience in this.

Please refer to [this comment](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/199#issuecomment-1216563916) for a starting point on writing tests for this use case.

2022-08-22 12:42 UTC, QuocDoBV commented
Hi @jonahgraham, 
Thanks a lot for your support!
I have created some tests to test for my new functionality. Could you take a look and review it help me?
This is the test reports [EditRegisterValue_Report_22082022.zip](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/files/9394389/EditRegisterValue_Report_22082022.zip)
Thank you so much!

2022-08-22 14:47 UTC, jonahgraham requested changes
Thanks @QuocDoBV for writing the tests. That makes it possible for me to properly review the change now. Please find my detailed line comments. Feel free to ask any follow up questions as needed.

2022-08-22 14:47 UTC, jonahgraham commented on src/GDBDebugSession.ts
> -            response.body = {
Unfortunately this change breaks functionality. There was no test for this, so I created PR #200 which adds such tests. Please rebase/merge the main branch into your change and you should see the issues.

If you run `'can read and set struct variables in a program'` in `var.spec.ts` without your change you will see this in the log*:

```
[14:27:25.546 UTC] From client: setVariable({"name":"y","value":"10","variablesReference":1002})
[14:27:25.547 UTC] GDB command: 35 -stack-info-depth 100
[14:27:25.547 UTC] GDB result: 35 done,depth="1"
[14:27:25.547 UTC] GDB command: 36 -var-assign var4.y 10
[14:27:25.547 UTC] GDB result: 36 done,value="10"
[14:27:25.548 UTC] To client: {"seq":0,"type":"response","request_seq":20,"command":"setVariable","success":true,"body":{"value":"10","variablesReference":0}}
```

But with this change the assumption that that if there is no varobj the set is for a register is too strong, so you get this:

```
[14:23:16.023 UTC] From client: setVariable({"name":"y","value":"10","variablesReference":1002})
[14:23:16.023 UTC] GDB command: 37 -stack-info-depth 100
[14:23:16.023 UTC] GDB result: 37 done,depth="1"
[14:23:16.023 UTC] GDB command: 38 -var-assign var4.y 10
[14:23:16.024 UTC] GDB result: 38 done,value="10"
[14:23:16.024 UTC] GDB command: 39 -data-list-register-values --frame 0 --thread 1 x
[14:23:16.037 UTC] GDB result: 39 done,register-values=[{number="0",value="0x3"},{number="1",value="0x5555555551f0"},{number="2",value="0x5555555551f0"},{number="3",value="0x1"},{number="4",value="0x7fffffffb748"},{number="5",value="0x1"},{number="6",value="0x7fffffffb650"},{number="7",value="0x7fffffffb600"},{number="8",value="0x0"},{number="9",value="0x7ffff7fe0d60"},{number="10",value="0xb"},{number="11",value="0x2"},{number="12",value="0x555555555060"},{number="13",value="0x7fffffffb740"},{number="14",value="0x0"},{number="15",value="0x0"},{number="16",value="0x555555555199"},{number="17",value="0x206"},{number="18",value="0x33"},{number="19",value="0x2b"},{number="20",value="0x0"},{number="21",value="0x0"},{number="22",value="0x0"},{number="23",value="0x0"},{number="24",value="0x0"},{number="25",value="0x0"},{number="26",value="0x0"},{number="27",value="0x0"},{number="28",value="0x0"},{number="29",value="0x0"},{number="30",value="0x0"},{number="31",value="0x0"},{number="32",value="0x37f"},{number="33",value="0x0"}
[14:23:16.037 UTC] GDB -cont-: 39 ,{number="34",value="0xffff"},{number="35",value="0x0"},{number="36",value="0x0"},{number="37",value="0x0"},{number="38",value="0x0"},{number="39",value="0x0"},{number="40",value="{v4_float = {0x0, 0x0, 0x0, 0x0}, v2_double = {0x0, 0x0}, v16_int8 = {0x0 <repeats 16 times>}, v8_int16 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int32 = {0x0, 0x0, 0x0, 0x0}, v2_int64 = {0x0, 0x0}, uint128 = 0x0}"},{number="41",value="{v4_float = {0x0, 0x0, 0x0, 0x0}, v2_double = {0x0, 0x0}, v16_int8 = {0x2f <repeats 16 times>}, v8_int16 = {0x2f2f, 0x2f2f, 0x2f2f, 0x2f2f, 0x2f2f, 0x2f2f, 0x2f2f, 0x2f2f}, v4_int32 = {0x2f2f2f2f, 0x2f2f2f2f, 0x2f2f2f2f, 0x2f2f2f2f}, v2_int64 = {0x2f2f2f2f2f2f2f2f, 0x2f2f2f2f2f2f2f2f}, uint128 = 0x2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f}"},{number="42",value="{v4_float = {0x0, 0x0, 0x0, 0x0}, v2_double = {0x0, 0x0}, v16_int8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v8_int16 = {0x0, 0x0, 0x0, 0xff, 0x0, 0x0, 0x0, 0x0}, v4_int32 = {0x0, 0
[14:23:16.037 UTC] GDB -cont-: 39 xff0000, 0x0, 0x0}, v2_int64 = {0xff000000000000, 0x0}, uint128 = 0xff000000000000}"},{number="43",value="{v4_float = {0x0, 0x0, 0x0, 0x0}, v2_double = {0x0, 0x0}, v16_int8 = {0x0 <repeats 16 times>}, v8_int16 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int32 = {0x0, 0x0, 0x0, 0x0}, v2_int64 = {0x0, 0x0}, uint128 = 0x0}"},{number="44",value="{v4_float = {0x0, 0x0, 0x0, 0x0}, v2_double = {0x0, 0x0}, v16_int8 = {0x0 <repeats 16 times>}, v8_int16 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int32 = {0x0, 0x0, 0x0, 0x0}, v2_int64 = {0x0, 0x0}, uint128 = 0x0}"},{number="45",value="{v4_float = {0x0, 0x0, 0x0, 0x0}, v2_double = {0x0, 0x0}, v16_int8 = {0x0 <repeats 16 times>}, v8_int16 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int32 = {0x0, 0x0, 0x0, 0x0}, v2_int64 = {0x0, 0x0}, uint128 = 0x0}"},{number="46",value="{v4_float = {0x0, 0x0, 0x0, 0x0}, v2_double = {0x0, 0x0}, v16_int8 = {0x0 <repeats 16 times>}, v8_int16 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int32 = {0x0, 0x0, 0
[14:23:16.037 UTC] GDB -cont-: 39 x0, 0x0}, v2_int64 = {0x0, 0x0}, uint128 = 0x0}"},{number="47",value="{v4_float = {0x0, 0x0, 0x0, 0x0}, v2_double = {0x0, 0x0}, v16_int8 = {0x0 <repeats 16 times>}, v8_int16 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int32 = {0x0, 0x0, 0x0, 0x0}, v2_int64 = {0x0, 0x0}, uint128 = 0x0}"},{number="48",value="{v4_float = {0x0, 0x0, 0x0, 0x0}, v2_double = {0x0, 0x0}, v16_int8 = {0x0 <repeats 16 times>}, v8_int16 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int32 = {0x0, 0x0, 0x0, 0x0}, v2_int64 = {0x0, 0x0}, uint128 = 0x0}"},{number="49",value="{v4_float = {0x0, 0x0, 0x0, 0x0}, v2_double = {0x0, 0x0}, v16_int8 = {0x0 <repeats 16 times>}, v8_int16 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int32 = {0x0, 0x0, 0x0, 0x0}, v2_int64 = {0x0, 0x0}, uint128 = 0x0}"},{number="50",value="{v4_float = {0x0, 0x0, 0x0, 0x0}, v2_double = {0x0, 0x0}, v16_int8 = {0x0 <repeats 16 times>}, v8_int16 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int32 = {0x0, 0x0, 0x0, 0x0}, v2_int64 = {0x0, 0x0}, uin
[14:23:16.037 UTC] GDB -cont-: 39 t128 = 0x0}"},{number="51",value="{v4_float = {0x0, 0x0, 0x0, 0x0}, v2_double = {0x0, 0x0}, v16_int8 = {0x0 <repeats 16 times>}, v8_int16 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int32 = {0x0, 0x0, 0x0, 0x0}, v2_int64 = {0x0, 0x0}, uint128 = 0x0}"},{number="52",value="{v4_float = {0x0, 0x0, 0x0, 0x0}, v2_double = {0x0, 0x0}, v16_int8 = {0x0 <repeats 16 times>}, v8_int16 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int32 = {0x0, 0x0, 0x0, 0x0}, v2_int64 = {0x0, 0x0}, uint128 = 0x0}"},{number="53",value="{v4_float = {0x0, 0x0, 0x0, 0x0}, v2_double = {0x0, 0x0}, v16_int8 = {0x0 <repeats 16 times>}, v8_int16 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int32 = {0x0, 0x0, 0x0, 0x0}, v2_int64 = {0x0, 0x0}, uint128 = 0x0}"},{number="54",value="{v4_float = {0x0, 0x0, 0x0, 0x0}, v2_double = {0x0, 0x0}, v16_int8 = {0x0 <repeats 16 times>}, v8_int16 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int32 = {0x0, 0x0, 0x0, 0x0}, v2_int64 = {0x0, 0x0}, uint128 = 0x0}"},{number="55",value="{v
[14:23:16.037 UTC] GDB -cont-: 39 4_float = {0x0, 0x0, 0x0, 0x0}, v2_double = {0x0, 0x0}, v16_int8 = {0x0 <repeats 16 times>}, v8_int16 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_int32 = {0x0, 0x0, 0x0, 0x0}, v2_int64 = {0x0, 0x0}, uint128 = 0x0}"},{number="56",value="0x1f80"},{number="57",value="0x0"},{number="58",value="0x0"},{number="59",value="0x0"},{number="60",value="0x0"},{number="61",value="0x0"},{number="62",value="0x0"},{number="63",value="0x0"},{number="64",value="0x0"},{number="65",value="0x0"},{number="66",value="0x0"},{number="67",value="0x0"},{number="68",value="0x0"},{number="69",value="0x0"},{number="70",value="0x0"},{number="71",value="0x0"},{number="72",value="0x0"},{number="152",value="0x7ffff7faf540"},{number="153",value="0x0"},{number="154",value="0xffffffffffffffff"},{number="155",value="0x3"},{number="156",value="0xf0"},{number="157",value="0xf0"},{number="158",value="0x1"},{number="159",value="0x48"},{number="160",value="0x1"},{number="161",value="0x50"},{number="162",value="0x0"},{number="
[14:23:16.037 UTC] GDB -cont-: 39 163",value="0x0"},{number="164",value="0x60"},{number="165",value="0xb"},{number="166",value="0x2"},{number="167",value="0x60"},{number="168",value="0x40"},{number="169",value="0x0"},{number="170",value="0x0"},{number="171",value="0x0"},{number="172",value="0x51"},{number="173",value="0x51"},{number="174",value="0x0"},{number="175",value="0x3"},{number="176",value="0x51f0"},{number="177",value="0x51f0"},{number=" [...]

2022-08-22 14:47 UTC, jonahgraham commented on src/GDBDebugSession.ts
> +                       break;
The indentation of this line does not look correct. Please run `yarn format` to format the code to the code standards.

2022-08-24 07:46 UTC, QuocDoBV commented on src/GDBDebugSession.ts
> -            response.body = {
Thanks a lot for your advice. It's very helpful to me. I revert it.

2022-08-24 07:53 UTC, QuocDoBV commented on src/integration-tests/var.spec.ts
> +            name: rn.name,
It's expected results. Some registers cannot edit. But I don't know how to create integration test in this case. I'm investigate to ignore this case when checking the returned result. 
Could you please give me some advices?
Thank a lot.

2022-08-24 07:55 UTC, QuocDoBV commented on src/integration-tests/var.spec.ts
> +        // (0, chai_1.expect)(vars.body.variables.length, 'There is a different number of registers than expected').to.equal(vars.body.variables.length);
I updated as your suggestion.
I learned a lot things from you.
Thank a lot.

2022-08-24 07:56 UTC, QuocDoBV commented on src/mi/var.ts
> +         command = `set $${params.varname} = ${params.expression}`;
I updated as your suggestion.
I learned a lot things from you.
Thank a lot.

2022-08-24 07:56 UTC, QuocDoBV commented on src/GDBDebugSession.ts
> +                       break;
I updated it.
It's very helpful.

2022-08-24 08:09 UTC, QuocDoBV commented
Hi @jonahgraham ,
I updated follow your suggestion. Some things  may not be good. Could you please help me review again.
This is the integration tests report.
[testResult_24_08.zip](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/files/9414148/testResult_24_08.zip)

2022-08-24 15:26 UTC, QuocDoBV commented on src/integration-tests/var.spec.ts
> +            name: rn.name,
You can get some problems like this when you enter a invalid value (abcd, @#...) to any local value (like the problem when editing a register which is not editable).

`15:03:28.792 UTC] GDB command: 24 -var-assign var1 a
[15:03:28.793 UTC] GDB result: 24 done,value="1"
[15:03:28.794 UTC] To client: {"seq":0,"type":"response","request_seq":11,"command":"setVariable","success":true,"body":{"value":"1","type":"int","variablesReference":0}}
[15:03:28.808 UTC] From client: disconnect(undefined)
[15:03:28.809 UTC] GDB command: 25 -gdb-exit
[15:03:28.817 UTC] GDB result: 25 exit
[15:03:28.817 UTC] GDB notify async: thread-exited,id="1",group-id="i1"
[15:03:28.817 UTC] GDB notify async: thread-group-exited,id="i1"
[15:03:28.829 UTC] To client: {"seq":0,"type":"response","request_seq":12,"command":"disconnect","success":true}`

This problem is expected to notice to user that the register cannot edit or user entered a invalid value.

2022-09-06 17:41 UTC, jonahgraham requested changes

2022-09-06 17:41 UTC, jonahgraham commented on src/GDBDebugSession.ts
> +                        let varobj = await mi.sendVarCreate(this.gdb, {
This creates vars that are never deleted, but the reference is lost because varobj is never saved. I don't know how big an issue this is, but it would be easily resolved with a sendVarDelete when you are done with it.

2022-09-06 17:41 UTC, jonahgraham commented on src/GDBDebugSession.ts
> +                        let varobj = await mi.sendVarCreate(this.gdb, {
PS - `varobj` looks `const`, so should be declared as such. In VScode this line displays as an error, if yours doesn't then perhaps you don't have [eslint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) installed?

![image](https://user-images.githubusercontent.com/679236/188697548-d4a61cc2-6496-4426-b903-d971ced22ab6.png)

2022-09-06 17:41 UTC, jonahgraham commented on src/integration-tests/utils.ts
> + export function verifyRegister(
There are a couple of minor formatting issues in and around this method - please make sure you run `yarn format` or setup [vscode to format on save](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode). Note if that was the only issue with the PR I would just fix formatting and merge. But it would help if code arrived already formatted.

2022-09-06 17:41 UTC, jonahgraham commented on src/GDBDebugSession.ts
> +                const result_values = await mi.sendDataListRegisterValues(
This block that does `sendDataListRegisterValues` and processes the result seems redundant to me. The `assign` variable has the value that needs to be returned, and because you set the format to hex with `sendVarSetFormatToHex`. I did a quick test and removing this new code (the changes in line 1053-1086) makes tests pass as expected. This also has the advantage of not unnecessarily reading all the registers because one is assigned.

2022-09-06 17:41 UTC, jonahgraham commented on src/integration-tests/var.spec.ts
> +            name: rn.name,
> Could you please give me some advices?

Only do assignment tests on r0, r1. 

> You can get some problems like this when you enter a invalid value (abcd, @#...) to any local value (like the problem when editing a register which is not editable).

Testing for this is a good idea, but it should be a separate test.

2022-09-06 17:41 UTC, jonahgraham commented on src/GDBDebugSession.ts
> +            let assign;
Why move this line?

2022-09-06 17:41 UTC, jonahgraham commented on src/integration-tests/var.spec.ts
> +        await dc.setVariableRequest({
You should test the return value of `setVariableRequest` as there is some not-insignificant code written to calculate it.

2022-09-07 12:34 UTC, QuocDoBV commented on src/GDBDebugSession.ts
> +                        let varobj = await mi.sendVarCreate(this.gdb, {
I have used a new solution.

2022-09-07 12:36 UTC, QuocDoBV commented on src/integration-tests/utils.ts
> + export function verifyRegister(
I have run yarn format after committing code

2022-09-07 12:36 UTC, QuocDoBV commented on src/GDBDebugSession.ts
> +                const result_values = await mi.sendDataListRegisterValues(
I have removed it.

2022-09-07 12:37 UTC, QuocDoBV commented on src/GDBDebugSession.ts
> +            let assign;
I have reverted it.

2022-09-07 12:41 UTC, QuocDoBV commented on src/integration-tests/var.spec.ts
> +        await dc.setVariableRequest({
I have updated the integration tests. If it's not what you want, please let me know I will update it.

2022-09-07 12:44 UTC, QuocDoBV commented
Dear @jonahgraham,
Could you please help me review again?
All integration tests passed.
This is the report file [integration_09072022_windows.zip](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/files/9506251/integration_09072022_windows.zip)

2022-09-07 12:47 UTC, QuocDoBV commented
Dear @jonahgraham,
I have also run integration tests on Linux OS.
This is the report file 
[integration_09072022_Linux.zip](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/files/9506272/integration_09072022_Linux.zip)

2022-09-07 12:50 UTC, jonahgraham commented
> Dear @jonahgraham, I have also run integration tests on Linux OS. This is the report file [integration_09072022_Linux.zip](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/files/9506272/integration_09072022_Linux.zip)

Hi @QuocDoBV - as [mentioned before](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/199#issuecomment-1221623542) please don't bother attaching xml files. The human readable output of the test is much more useful. Also if all the tests are passing I don't need to see anything, you can just tell me they all passed.

2022-09-07 13:48 UTC, jonahgraham requested changes
This is mostly fine - just needs some polishing and the missing test.

2022-09-07 13:48 UTC, jonahgraham commented on src/GDBDebugSession.ts
> +            if (varobj == null && ref.type === 'registers') {
Should this be `if (!varobj && ref.type === 'registers') {`? I assume that `getVar` returns `undefined` when the var object doesn't exist already. In this case you are coercing the `undefined` to `null`. You should probably be using the [falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy) nature of varobj, just like the other if statements do.. See this good SO answer for more details https://stackoverflow.com/a/5101991/2796832

2022-09-07 13:48 UTC, jonahgraham commented on src/GDBDebugSession.ts
> +                await mi.sendVarSetFormatToHex(this.gdb, varobj.varname);
I think you should do `sendVarSetFormatToHex` when the var is created - it should only need to be done once. Then this if block and the else if becomes the same (just the `sendVarAssign`)

2022-09-07 13:48 UTC, jonahgraham commented on src/integration-tests/utils.ts
> + export function verifyRegister(
OK - you need to commit and push the format change too. AFAICT this is still badly formatted.

2022-09-07 13:48 UTC, jonahgraham commented on src/integration-tests/var.spec.ts
> +        await dc.setVariableRequest({
You still aren't checking the return value of `setVariableRequest` Please see the change I did for PR #200 to get an idea of what is missing. Note that the response of `setVariableRequest` is what is displayed back to the user in VScode after making an edit to the register.

2022-09-07 13:48 UTC, jonahgraham commented on src/GDBDebugSession.ts
> +                varobj = this.gdb.varManager.addVar(
I don't think this var obj ever gets removed?

2022-09-08 03:21 UTC, QuocDoBV commented on src/GDBDebugSession.ts
> +            if (varobj == null && ref.type === 'registers') {
I have updated it. Thanks a lot for your additional information.

2022-09-08 03:21 UTC, QuocDoBV commented on src/GDBDebugSession.ts
> +                await mi.sendVarSetFormatToHex(this.gdb, varobj.varname);
I have updated it.

2022-09-08 03:22 UTC, QuocDoBV commented on src/GDBDebugSession.ts
> +                varobj = this.gdb.varManager.addVar(
I have added test to check the return value of setVariableRequest.

2022-09-08 03:27 UTC, QuocDoBV commented on src/GDBDebugSession.ts
> +                varobj = this.gdb.varManager.addVar(
> I don't think this var obj ever gets removed?

Could you teach me why we should remove var obj and what cases we should remove? Actually, I don't know when we should remove it.

2022-09-08 03:31 UTC, QuocDoBV commented
Dear @jonahgraham,
Could you please help me review again?
This is the log file in my environment
[log08092022.zip](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/files/9523375/log08092022.zip)
Thank you so much for your helpful tips.

2022-09-08 12:54 UTC, jonahgraham requested changes
I will do the requested change.

2022-09-08 12:54 UTC, jonahgraham commented on src/GDBDebugSession.ts
> +                varobj = this.gdb.varManager.addVar(
Because we accumulate var objects forever otherwise. If it is just a few extra var objects that really won't matter, but if someone has a debug session running for a long time they don't want to have new var objects forever.

However, I don't know how big a problem this is in practice AFAICT the var objects will be reused for the same combination of register/thread/frame. 

As this is the only outstanding issue I think I will add the comment and submit now.

2022-09-08 13:17 UTC, jonahgraham requested changes
There is still a serious bug in this code. I am sorry I didn't see it before now. Consider the use case where a user modified a register which has the same name as a local variable (e.g. `rax`).

Here is a log of the problem with my comments:

```

# VScode requests scopes, as you can see ref 1000 is for Local variables and 1001 is for registers
From client: scopes({"frameId":1000})
To client: {"seq":0,"type":"response","request_seq":17,"command":"scopes","success":true,"body":{"scopes":[{"name":"Local","variablesReference":1000,"expensive":false},{"name":"Registers","variablesReference":1001,"expensive":true}]}}

# Here VScode requests variables for reg 1000 (locals)...
From client: variables({"variablesReference":1000})
GDB command: 25 -stack-info-depth 100
GDB result: 25 done,depth="1"
GDB command: 26 -stack-list-variables --thread 1 --simple-values
GDB result: 26 done,variables=[{name="rax",type="int",value="1"}]
# ... and the adapter creates var4 for accessing local variable rax
GDB command: 27 -var-create --thread 1 --frame 0 - * "rax"
GDB result: 27 done,name="var4",numchild="0",value="1",type="int",thread-id="1",has_more="0"

# Here VScode resuests the registers
# eliding GDB responses for getting register names and values because they are very long
From client: variables({"variablesReference":1001})
GDB command: 28 -data-list-register-names --frame 0 --thread 1
GDB command: 29 -data-list-register-values --frame 0 --thread 1 x
To client: {"seq":0,"type":"response","request_seq":19,"command":"variables","success":true,"body":{"variables":[{"name":"rax","evaluateName":"$rax","value":"0x1","variablesReference":0}, # -- snip

# Here VSCode is trying to set the register rax
From client: setVariable({"variablesReference":1001,"name":"rax","value":"1234"})
GDB command: 30 -stack-info-depth 100
GDB result: 30 done,depth="1"

# But it is var4 that is assigned - which is the varobj for the local variable
GDB command: 31 -var-assign var4 1234
GDB result: 31 done,value="1234"
```

@QuocDoBV  Please resolve this (and while at it you can add the comments covering the design decision to not delete the varobjs).

2022-09-08 13:17 UTC, jonahgraham commented on src/GDBDebugSession.ts
> +                    args.name,
This varobj is stored in the varManager in a way that it indistinguishable from a local variable of the same name.

2022-09-08 13:18 UTC, jonahgraham commented
> There is still a serious bug in this code. I am sorry I didn't see it before now. Consider the use case where a user modified a register which has the same name as a local variable (e.g. `rax`).

PS Please create a test case for this usage scenario to make sure that it doesn't regress later.

2022-09-12 04:25 UTC, QuocDoBV commented on src/GDBDebugSession.ts
> +                    args.name,
I have fixed it.

2022-09-12 04:26 UTC, QuocDoBV commented
> > There is still a serious bug in this code. I am sorry I didn't see it before now. Consider the use case where a user modified a register which has the same name as a local variable (e.g. `rax`).
> 
> PS Please create a test case for this usage scenario to make sure that it doesn't regress later.

I have created test cases to cover it.

2022-09-12 04:29 UTC, QuocDoBV commented
Dear @jonahgraham,
I have fixed issue related to editing register which has the same name with local variable.
Could you please help me review it again.
You can check the log file to have more details [log09122022.zip](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/files/9544625/log09122022.zip)

2022-09-12 17:20 UTC, merged

2022-09-12 17:20 UTC, jonahgraham commented
Thank you @QuocDoBV for the new code and for good new tests to keep it working into the future too.