Support set Hardware Breakpoint when debugging
eclipse-cdt-cloud/cdt-gdb-adapter pull request #218
Opened 2022-09-26 09:32 UTC by thamho0902

Root-cause: VS Code does not have option to set hardware breakpoint when debugging.
=> Solution: Add option for selecting use hardware breakpoint or software breakpoint by config in launch.json file

2022-09-26 19:04 UTC, jonahgraham requested changes
This comment is design decision question, I would appreciate your thoughts on this before we merge it.

I'm not sure this is the correct solution to HW breakpoints. It may be suitable for now, but in particular I think `hardware-breakpoint-limit` should be configurable and set along with turning on hardware breakpoints.

IIRC the other way to get gdb to do this is to set `hardware-breakpoint-limit` and set all memory to be `ro` and let gdb manage it automatically.

2022-09-27 03:11 UTC, danghaibang-banvien commented on src/mi/breakpoint.ts
> +    const hwBreakpoint = request.hardwareBreakpoint ? '-h -f ' : '';
Hi @jonahgraham-san,
1. I will change for function breakpoint in the next patch set.
2. I see in e2studio using the argument "-f" for send command set breakpoint. But when I test with VS Code, It seems not to impact debugging.
3. Do you mean we need to write a regression test for this ticket?
Thank you.

2022-09-27 16:24 UTC, jonahgraham commented
> This comment is design decision question, I would appreciate your thoughts on this before we merge it.
> 
> I'm not sure this is the correct solution to HW breakpoints. It may be suitable for now, but in particular I think `hardware-breakpoint-limit` should be configurable and set along with turning on hardware breakpoints.
> 
> IIRC the other way to get gdb to do this is to set `hardware-breakpoint-limit` and set all memory to be `ro` and let gdb manage it automatically.

Please share your comments on the above before I consider merging.

2022-09-27 16:38 UTC, jonahgraham requested changes
In addition to these comments, there are [unanswered questions from the last patchset](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/218#pullrequestreview-1120741070).

> 1. I will change for function breakpoint in the next patch set.

Thank you.

> 2. I see in e2studio using the argument "-f" for send command set breakpoint. But when I test with VS Code, It seems not to impact debugging.

Do you know what `-f` does? It may be important in some circumstances, but it is likely just as important for software as hardware breakpoints. If you need `-f`, the `pending` in requests should be used.

From https://sourceware.org/gdb/current/onlinedocs/gdb/GDB_002fMI-Breakpoint-Commands.html:
`-f` If _locspec_ cannot be resolved (for example if it refers to unknown files or functions), create a pending breakpoint. Without this flag, GDB will report an error, and won’t create a breakpoint, if _locspec_ cannot be parsed.



> 3. Do you mean we need to write a regression test for this ticket?

Yes. Always, for all tickets. If for some reason you can't, you should document that fact in the PR somewhere. Non-exhaustive list of possible reasons to not include a new test:
- Code being modified is already well exercised by existing tests
- Code being modified requires custom setup that is beyond the ability to test in the current suite (e.g. performance changes)

>  Additional information, we have tested with CVe Linux, and hardware breakpoint can set and hit normally.

This is useful information.

2022-09-27 16:38 UTC, jonahgraham commented on src/mi/breakpoint.ts
> +        hardwareBreakpoint: boolean;
Sorry I missed this before, but please reuse `hardware` which is already present rather than creating a new option.

2022-09-27 16:38 UTC, jonahgraham commented on src/mi/breakpoint.ts
> +        hardwareBreakpoint: boolean;
:-( - Unfortunately I didn't realize this before, but the parameters for `sendBreakFunctionInsert` are quite different than `sendBreakInsert`, but they really should be basically the same.

Any suggestion on how to resolve this? You can include that in this change, just note it in the commit comment so when we make a changelog we can see that. 

At the moment this change already breaks the API anyway (new required parameter), so lets see if we can do it properly.

PS I may have to sleep on this and see if we should be making this change backwards compatible or not.

2022-09-27 16:39 UTC, jonahgraham commented on src/mi/breakpoint.ts
> +    const hwBreakpoint = request.hardwareBreakpoint ? '-h -f ' : '';
I have moved this thread to the main feedback of the change.

2022-09-28 01:58 UTC, danghaibang1999 commented on src/mi/breakpoint.ts
> +        hardwareBreakpoint: boolean;
Yes, I missed this argument, it had option hardware breakpoint before. Thank you.

2022-09-28 02:15 UTC, danghaibang1999 commented
> Do you know what -f does? It may be important in some circumstances, but it is likely just as important for software as hardware breakpoints. If you need -f, the pending in requests should be used.
I see all breakpoint types in e2 studio always have option '-f'. If the decision is using '-f' option, I think it needs to fix in command send to GDB server. 
(example: const command = `-break-insert ${temp}${hwBreakpoint}${ignore} **-f** ${location}`;)

> Yes. Always, for all tickets. If for some reason you can't, you should document that fact in the PR somewhere. Non-exhaustive list of possible reasons to not include a new test:
I will write the integration test if possible. Or not, I will update document in Jira/Confluence ticket.
Thank you.

2022-09-28 02:53 UTC, danghaibang1999 commented
> This comment is design decision question, I would appreciate your thoughts on this before we merge it.

I'm not sure this is the correct solution to HW breakpoints. It may be suitable for now, but in particular I think hardware-breakpoint-limit should be configurable and set along with turning on hardware breakpoints.

IIRC the other way to get gdb to do this is to set hardware-breakpoint-limit and set all memory to be ro and let gdb manage it automatically.

I am trying to use command '-gdb-set breakpoint auto-hw on' in launch process but it seems not to affect the type of breakpoint.
It is also for option 'hardware-breakpoint-limit', I am not sure if we have the special config for it or not but the command sent to Renesas GDB server has an error (cannot set option limit or unlimited).
So, I think using the current solution can be helpful, The extension has a limit in UI (has only the option "Add breakpoint" but cannot choose the type of breakpoint). I think the exact way is to improve the breakpoint widget to have an option "Add hardware breakpoint", but it seems not available for now.
I think my solution is fixing temporarily, if users do not care type of breakpoint, it is not configured in the launch file and software breakpoint is used for default.
Thank you.

2022-09-28 04:55 UTC, danghaibang1999 commented on src/mi/breakpoint.ts
> +        hardwareBreakpoint: boolean;
I see `sendBreakFunctionInsert ` also supports `temporary`, `pending `, and `hardware ` commands. I think it has the argument same as the `sendBreakInsert` function.

> Any suggestion on how to resolve this? You can include that in this change, just note it in the commit comment so when we make a changelog we can see that.

I propose a solution that adds condition `?`  in parameter `request`. It seems this argument can be used or not. I can work compatible with the previous code. What do you think about it?

2022-09-28 05:57 UTC, jonahgraham commented
> I will write the integration test if possible. Or not, I will update document in Jira/Confluence ticket.

Great. Please also document the reasoning here. This is an open source project and we should try not to put cdt-gdb-adapater specific information in systems that are not visible to everyone. It is complicated because I have access to the JIRA, but imagine the reviewer of these PRs didn't.

2022-09-28 13:41 UTC, jonahgraham requested changes
> I think my solution is fixing temporarily, if users do not care type of breakpoint, it is not configured in the launch file and software breakpoint is used for default. Thank you.

Sounds good, and I agree and will merge it once review comments are resolved. Thank you for including your reasoning. This is important both for the review, but also for someone who comes along in the future and wants to understand the _why_ we did something this way.

2022-09-28 13:41 UTC, jonahgraham commented on src/integration-tests/utils.ts
> +export const hardwareBreapoint: boolean =
This doesn't seem to be connected to anything. I think you want to add something to `fillDefaults` a few lines above this.

Additionally, this is an OK way to test the new functionality. Also acceptable is a single test added to `breakpoints.spec.ts` and `functionBreakpoints.spec.ts` that sets `hardwareBreakpoint`.

2022-09-28 13:41 UTC, jonahgraham commented on package.json
> +    "test": "yarn test:integration && yarn test:integration-remote-target && yarn test:integration-gdb-async-off && yarn test:integration-gdb-async-off-remote-target && yarn test:integration-gdb-non-
Can you make the same two changes to this file to the `test-ci` version please.

PS - if you have ideas on how to simplify all the `test` and `test-ci` scripts in `package.json` that would be great (but do it in a different PR though)

2022-09-28 13:41 UTC, jonahgraham commented on src/integration-tests/utils.ts
> +    process.argv.indexOf('--test-hw-breakpoint-on') === -1;
I think your conditional is backwards here. `indexOf` returns `-1` when the item is _not_ found.

2022-09-29 08:06 UTC, danghaibang1999 commented on src/integration-tests/utils.ts
> +    process.argv.indexOf('--test-hw-breakpoint-on') === -1;
I have fixed it. Thank you.

2022-09-29 08:06 UTC, danghaibang1999 commented on package.json
> +    "test": "yarn test:integration && yarn test:integration-remote-target && yarn test:integration-gdb-async-off && yarn test:integration-gdb-async-off-remote-target && yarn test:integration-gdb-non-
Done. Thank you.

2022-09-29 08:13 UTC, danghaibang1999 commented on src/integration-tests/utils.ts
> +export const hardwareBreapoint: boolean =
I added new TCs for `breakpoints.spec.ts` and `functionBreakpoints.spec.ts`. It runs ok in case of software breakpoint, but in case of hardware breakpoint, gdb for running test is not supported hardware breakpoint, and all TCs are failed. I cannot check the output of it in this case. Do you have any idea about it? Thank you.

2022-09-29 15:13 UTC, jonahgraham requested changes

2022-09-29 15:13 UTC, jonahgraham commented on src/integration-tests/utils.ts
> +export const hardwareBreapoint: boolean =
Here is the log extract:


```
[08:25:52.736 UTC] GDB command: 5 -break-insert -h --source "/home/runner/work/cdt-gdb-adapter/cdt-gdb-adapter/src/integration-tests/test-programs/count.c" --line 4
[08:25:52.737 UTC] GDB result: 5 error,msg="No hardware breakpoint support in the target."
[08:25:52.737 UTC] To client: {"seq":0,"type":"response","request_seq":3,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"verified":false,"message":"No hardware breakpoint support in the target."}]}}
```

Hardware breakpoints aren't generally supported by host dev, but it should work on remote, at least on linux. You may need to do skip for unsupported platforms, e.g. see:

https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/blob/9d7b824523c2ec8abf5635c900ed2cd100812457/src/integration-tests/utils.ts#L254-L257

2022-09-30 08:20 UTC, danghaibang1999 commented on src/integration-tests/utils.ts
> +    args.hardwareBreakpoint = hardwareBreapoint;
Done. Thank you.

2022-09-30 08:20 UTC, danghaibang1999 commented on src/integration-tests/functionBreakpoints.spec.ts
> +        expect(outputs.body.output.includes(substring)).eq(true);
Done. Thank you.

2022-09-30 08:37 UTC, thamho0902 commented
Sorry, I have a mistake. Please help me check again.

2022-09-30 10:41 UTC, danghaibang1999 commented
Hi @jonahgraham-san,
It seems running test in windows have failed because option '--timeout 5000' in file package.json

> 1) "before all" hook in "{root}":
     Error: Command failed: make
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot open output file empty.exe: Permission denied
collect2.exe: error: ld returned 1 exit status
mingw32-make: *** [makefile:30: empty] Error 1
      at checkExecSyncError (child_process.js:790:11)
      at Object.execSync (child_process.js:863:15)
      at Context.<anonymous> (src\integration-tests\utils.ts:251:12)
      at processImmediate (internal/timers.js:464:21)

I have no solution for this. Could you please help me give me your idea? Thank you.

2022-09-30 13:56 UTC, jonahgraham approved these changes
Rather than bounce it back to you one more time, I have fixed the remaining items (including formatting, which at some point I will add to the CI so you can be immediately notified if formatting/linting is incorrect)

Please do take the time to review the commits I pushed to your branch so you can know what and why I changed some items.

2022-09-30 13:56 UTC, jonahgraham commented on package.json
> +    "test-ci": "run-s --continue-on-error test-ci:integration test-ci:integration-remote-target test-ci:integration-gdb-async-off test-ci:integration-gdb-async-off-remote-target test-ci:integration-g
Why did you remove the hw breakpoints tests in this commit?

2022-09-30 13:56 UTC, jonahgraham commented on package.json
> +    "test-ci": "run-s --continue-on-error test-ci:integration test-ci:integration-remote-target test-ci:integration-gdb-async-off test-ci:integration-gdb-async-off-remote-target test-ci:integration-g
I added the following commit:

[Restore running hw breakpoint tests as part of test and test-ci](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/218/commits/ea655665ec2fcb3429274e18636fd62b3e40b122) 
[ea65566](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/218/commits/ea655665ec2fcb3429274e18636fd62b3e40b122)

Note that I think the reason that you removed them is because the test-ci:integration-hw-breakpoint-on-remote-target was missing the --skip-make command line option. On the CI machine we can't run make reliably from within the mocha tests, so that is why I decided to split the make step out in commit

2022-09-30 13:56 UTC, jonahgraham commented on src/integration-tests/functionBreakpoints.spec.ts
> +            // If cannot get correct event, program timeout and test case failed.
I added the commit:
[Use the global timeout](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/218/commits/7576a29202407e54b6d9838c1abafbab83755a48) 
[7576a29](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/218/commits/7576a29202407e54b6d9838c1abafbab83755a48)
See issue https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/issues/222 and the fix there for more details as to why.

2022-09-30 13:57 UTC, merged

2022-09-30 14:04 UTC, danghaibang1411 commented on package.json
> +    "test-ci": "run-s --continue-on-error test-ci:integration test-ci:integration-remote-target test-ci:integration-gdb-async-off test-ci:integration-gdb-async-off-remote-target test-ci:integration-g
Hi @jonahgraham-san,
Sorry this is my mistake. When I change the code for fixing build in Github, I forgot this item. Thank for your support.

2022-09-30 14:07 UTC, danghaibang1411 commented on src/integration-tests/functionBreakpoints.spec.ts
> +            // If cannot get correct event, program timeout and test case failed.
Yes, I have seen your commit and fix for the previous build fail in this ticket. Thank you.