Support Memory Browser for multiple child
eclipse-cdt-cloud/cdt-gdb-adapter pull request #226
Opened 2022-11-29 11:19 UTC by trongle0504

Support Memory Browser for multiple children

2022-11-30 02:11 UTC, jonahgraham requested changes
I haven't looked at the next layers in the stack yet, but these changes don't look like they belong here. Especially a required new field in an arguments interface requires strong justification/explanation and tests.

2022-11-30 02:11 UTC, jonahgraham commented on src/GDBDebugSession.ts
> +            if (args.address === '') {
Any changes in cdt-gdb-adapter require tests. Please provide a test along with explanation about what this code is changing.

2022-12-08 06:53 UTC, trongle0504 commented on src/GDBDebugSession.ts
> +    child?: string[];
It doesn't remain after changing the code.

2022-12-08 06:54 UTC, trongle0504 commented on src/GDBDebugSession.ts
> +            if (args.address === '') {
It doesn't remain after changing the code

2022-12-08 19:01 UTC, jonahgraham requested changes
I think this change should simply be closed.

2022-12-08 19:01 UTC, jonahgraham commented on src/GDBDebugSession.ts
> +        } else if ('cdt-amalgamator/getChildDapNames') {
The adapter doesn't/shouldn't need to know about custom messages of the amalgamator. The client code can issue this command, and handle the case where it fails.

2022-12-09 09:17 UTC, trongle0504 commented
No need changes with new solution

2022-12-09 09:17 UTC, closed without merging