Allow pre-filling launch/attach on command line to adapter
eclipse-cdt-cloud/cdt-gdb-adapter pull request #228
Opened 2023-01-18 20:34 UTC by jonahgraham

This change adds an optional command line argument --config=JSON or --config=@/path/to/file that will provide the default values of all the provided arguments to launch/attach request.

This change allows users to start the adapter to pre-fill the program, gdb, or any other field needed. Some usage examples:

```sh
node debugAdapter.js --config='{"program":"/path/to/my.elf"}'

node debugTargetAdapter.js --config='{"gdb":"arm-none-eabi-gdb", "port": 1234}'

cat >config.json <<END
{
  "processId": 1234
}
END
node debugAdapter.js --config=@config.json
```

Fixes #227

2023-01-19 11:26 UTC, thegecko commented
Thanks @jonahgraham, this is exactly what I was thinking.

A couple of observations considering the "server" owner should potentially own the setup configuration.

- Should the server somehow dictate whether the session is a `launch` or `attach`? 
- When configuration is specified in the server, could it be a security concern to allow the client to override the data?

e.g. considering:
```typescript
            args = {
                ...GDBDebugSession.commandLineLaunchAttachArguments,
                ...args,
            };
```

A situation could exist where a remote server specifies the binary to be debugged, but the remote client can override this and point at arbitrary binaries.

For now I don't belive these points should block merging, though!

2023-01-19 14:38 UTC, jonahgraham commented
> For now I don't belive these points should block merging, though!

OK. I'll test this draft works and work towards merging.

> Should the server somehow dictate whether the session is a launch or attach?
> When configuration is specified in the server, could it be a security concern to allow the client to override the data?

I'll consider how to address this as I test.

2023-01-23 18:34 UTC, jonahgraham commented
Updated description to include details on `--config-frozen` that I added to address @thegecko's concerns raised.

2023-01-23 18:35 UTC, jonahgraham commented
@thegecko this is ready for review (docs + tests done)

2023-01-23 20:12 UTC, jonahgraham commented
The change (hopefully just the tests) don't work on Windows. I'll have to spin up there to figure out what went wrong, but my guess is it has to do with how we are passing the extra args in the debug adapter launch here:

https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/blob/2ceef5b03b0cfd8b70cb6fcaf386e19ff17670a9/src/integration-tests/utils.ts#L193-L203

That code relies on shell=true so that all the arguments can be passed as one parameter, but with all the quoting my guess is on Windows the shell handling causes the arguments to be split in the wrong place. I have some WIP on allowing this in cdt-gdb-adapter [here](https://github.com/jonahgraham/cdt-gdb-adapter/tree/args-to-commandline), but the better solution would be to fix it upstream, probably [like this](https://github.com/jonahgraham/vscode-debugadapter-node/commit/9661b841afc2d1f96d60301dc012d107712c5a60), but that isn't tested.

2023-01-24 16:32 UTC, thegecko requested changes
A small request to remove a check, but apart from that this works well for me. I'll share an example of it in use shortly

2023-01-24 16:32 UTC, thegecko commented on src/GDBDebugSession.ts
> +        const frozenRequest = GDBDebugSession.frozenRequestArguments?.request;
Can this check be removed?

The reason is a little convoluted, but I'll try...

- The server owner sets up the debugger container and chooses `attach` or `launch` for GDB. In my test case I'm using `launch`.
- From a remote VSCode client connection, you are always `attach`ing to the remote running instance, so that's the way I'm specifying to connect to a remote system rather than launching something.

So the above scenario throws an error when in fact the launch type from the client should just be ignored. Therefore I think this check shouldn't be enforced.

2023-01-24 16:45 UTC, jonahgraham commented on src/GDBDebugSession.ts
> +        const frozenRequest = GDBDebugSession.frozenRequestArguments?.request;
I'll wait for your example as that may clarify, but not sure I understand. If VSCode does attach request, how does the adapter run the launch request code?

BTW here I am talking about whether the adapter launches or attaches to the target, as opposed to whether VSCode launches or attaches to the adapter. Is that where my confusion lies?

How are you attaching VSCode to the adapter, are you using `debugServer` or will you implement a custom launch code using `DebugAdapterDescriptor`/`DebugAdapterServer`?

Regardless, I am fine to remove the check.

2023-01-24 17:04 UTC, thegecko commented on src/GDBDebugSession.ts
> +        const frozenRequest = GDBDebugSession.frozenRequestArguments?.request;
Example uploaded here:

https://github.com/thegecko/cdt-gdb-adapter-docker

2023-01-24 17:56 UTC, jonahgraham commented on src/GDBDebugSession.ts
> +        const frozenRequest = GDBDebugSession.frozenRequestArguments?.request;
Thanks. I had a look at that and I understand almost what is happening.

What I don't understand is when the "attach" request in the launch.json turns into a "launch" request in cdt-gdb-adapter. IIUC VSCode will start the arm-debug adapter, and then send it an "attachRequest", so presumably arm-debug then connects to the given address and sends an initializeRequest + launchRequest?

2023-01-24 18:06 UTC, thegecko commented on src/GDBDebugSession.ts
> +        const frozenRequest = GDBDebugSession.frozenRequestArguments?.request;
I thought you might notice this. It's currently a hack which will be removed from our adapter shortly.

By the way, happy to jump on a call and discuss all this, I want to get it right (and not just for our use case!)

2023-01-24 18:14 UTC, jonahgraham commented on src/GDBDebugSession.ts
> +        const frozenRequest = GDBDebugSession.frozenRequestArguments?.request;
I can do right now if you are available. Send me an email, or I have a zoom account I can send you an invite.

2023-01-24 19:59 UTC, jonahgraham commented
> The change (hopefully just the tests) don't work on Windows. 

Windows issues have been fixed, all CI green now.

2023-01-25 17:47 UTC, jonahgraham commented
@thegecko As discussed I have refactored launch/attach request to have a true common code for both of them in 594348825e0a76185e0e0469e91bb39a3bf21a17

The final commit 55510156bd2231a9f30bdc408a2387505c5f586d in this series is the implementation of the feature request. The preceding commits are all the cleanup/refactoring that I did to make it easier to read and review 55510156bd2231a9f30bdc408a2387505c5f586d

2023-01-26 11:35 UTC, thegecko approved these changes
Thanks @jonahgraham. I tested passing an `attach` config with a frozen `launch` server config and all works as expected.

I'd be keen to see a new release when this gets merged :)

2023-01-26 14:43 UTC, merged