Update GDBDebugSession.ts
eclipse-cdt-cloud/cdt-gdb-adapter pull request #234
Opened 2023-01-29 06:16 UTC by Noneghost

fix a bug that frontend ui don't stop when program run over too quickly.

2023-01-30 22:36 UTC, jonahgraham commented
Hi @Noneghost, thank you for the PR. Before we can consider the PR we need the ECA to be signed. See [here](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/blob/main/CONTRIBUTING.md#eclipse-contributor-agreement) for more details.

2023-01-31 01:31 UTC, Noneghost commented
> Hi @Noneghost, thank you for the PR. Before we can consider the PR we need the ECA to be signed. See [here](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/blob/main/CONTRIBUTING.md#eclipse-contributor-agreement) for more details.

Hi @jonahgraham , I haved signed eca 3.1.0.

2023-01-31 03:11 UTC, jonahgraham requested changes
Thanks for the fix, it looks correct to me and I can manually that this fixes the problem. AFAICT it isn't limited to just short running programs. If I add a breakpoint in main somewhere and then continue I also don't get the terminated event from the adapter.

A new test is needed to make sure that terminated event arrives. Using launch.spec.ts as a starting point and then issuing a continue request and verifying a terminate event arrives would probably suffice.

If there is a timing thing going on that is much more annoying as it is difficult to test automatically.

2023-01-31 21:33 UTC, GitMensch commented
So, possibly take in, if we already know that there's an issue which is fixed by this? (I'm seeing the same issue - process is terminated but still "active" in the UI).

2023-01-31 21:40 UTC, jonahgraham commented
> So, possibly take in, [...]

Sorry, I don't know what you mean by this part?

2023-01-31 21:44 UTC, GitMensch commented
If you know that the known bug is fixed I suggest to pull that as-is, and adding "more missing things" later.

2023-02-04 14:37 UTC, merged