Support resume all sessions
eclipse-cdt-cloud/cdt-gdb-adapter pull request #255
Opened 2023-02-09 11:45 UTC by trongle0504

Adding a "Resume All" button to support resuming all sessions using the amalgamator.

2023-02-10 02:44 UTC, jonahgraham requested changes
I believe all the changes to cdt-gdb-adapter are unneeded.

2023-02-10 02:44 UTC, jonahgraham commented on src/GDBDebugSession.ts
> +            this.sendEvent(new ContinuedEvent(args.threadId));
Don't send events here, make the amalgamator send a normal continue request and then generate the extra events needed as discussed in https://github.com/eclipse-cdt-cloud/cdt-gdb-vscode/pull/80#discussion_r1102220588

2023-02-13 09:33 UTC, trongle0504 commented on src/GDBDebugSession.ts
> +            this.sendEvent(new ContinuedEvent(args.threadId));
I have removed the event submission here. However, in this repository, we need to check the thread states at the `continueRequest()` function before sending `mi.sendExecContinue() ` to GDB. The purpose of this is to avoid the error `'Cannot execute this command while the selected thread is running.'`

2023-02-13 15:18 UTC, jonahgraham requested changes

2023-02-13 15:18 UTC, jonahgraham commented on src/GDBDebugSession.ts
> +            if(this.isRunning === false) {
Please don't suppress this error. If the client asks to resume, but the thread is running already the adapter should send back an error indicating that.

This is especially true since your check doesn't match the continue arguments. You are checking against the state of all threads, but may be resuming just a single thread.

2023-02-14 09:06 UTC, trongle0504 commented
This pull request is closed because the code was executed at cdt-amalgamator.

2023-02-14 09:06 UTC, closed without merging