Make a delay to GDB server to be terminated
eclipse-cdt-cloud/cdt-gdb-adapter pull request #256
Opened 2023-02-15 07:18 UTC by QuocDoBV

When restart request is called, the disconnectRequest() and launchRequest() will be called. In the disconnectRequest() will send a '-gdb-exit' command to exit GDB server then the launch method will be called to start a new GDB server. But LaunchRequest() is not wait for GDB server is terminated completely to run and start a new GDB server. In this case, Emulator is still being held by old GDB server, So cannot start a new GDB server. Solution: Make a delay to wait for GDB server is terminated completely.

2023-02-15 07:19 UTC, QuocDoBV commented
Hi @jonahgraham-san,
Could you help me review the PR?
Thank you!

2023-02-15 15:36 UTC, jonahgraham requested changes
This feels like the wrong way to go about it. A forced 5 second delay on all restarts is too much of a hack. Instead I think you need to override disconnect request in the target debug session and actually monitor the target server process, possibly forcibly killing it if it doesn't exit after a reasonable amount of time.

Note that #253 that was raised recently is a similar issue because it also talks about how to handle exiting the target server.

2023-02-15 15:36 UTC, jonahgraham commented on src/GDBDebugSession.ts
> +            if(_args.restart){
_This comment is for educational purposes as I don't think this change will be kept once the overall review is addressed._

the `_` prefixed variables are named as such to prevent unused variable warnings from the linter:

https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/blob/4f6f0fa6e0050a7c50d1d45af4a2c30785f0f14c/.eslintrc.js#L16-L22

Also, the formatting of this if block looks incorrect. I recommend enabling format on save using the prettier configuration.

2023-02-17 10:21 UTC, QuocDoBV commented
Hi @jonahgraham,
Could you please help me review the new code?
Thank you!

2023-02-21 14:12 UTC, jonahgraham requested changes
On the whole this change is definitely in the correct direction.

I have a number of questions in the review. I have not done work in this area so please feel free to simply explain your reasons. If my questions open up new ideas, that is great too.

We really need tests for this type of code. Here is something that may be useful for you as a starting point (I did this while experimenting on #253)

```diff
diff --git a/src/integration-tests/launchRemote.spec.ts b/src/integration-tests/launchRemote.spec.ts
index 63f861a..f219274 100644
--- a/src/integration-tests/launchRemote.spec.ts
+++ b/src/integration-tests/launchRemote.spec.ts
@@ -16,8 +16,8 @@ import {
 import { CdtDebugClient } from './debugClient';
 import { fillDefaults, standardBeforeEach, testProgramsDir } from './utils';
 
-describe('launch remote', function () {
-    let dc: CdtDebugClient;
+describe.only('launch remote', function () {
+    let dc: CdtDebugClient | undefined;
     const emptyProgram = path.join(testProgramsDir, 'empty');
     const emptySrc = path.join(testProgramsDir, 'empty.c');
 
@@ -26,11 +26,11 @@ describe('launch remote', function () {
     });
 
     afterEach(async function () {
-        await dc.stop();
+        await dc?.stop();
     });
 
     it('can launch remote and hit a breakpoint', async function () {
-        await dc.hitBreakpoint(
+        await dc?.hitBreakpoint(
             fillDefaults(this.test, {
                 program: emptyProgram,
                 target: {
@@ -43,4 +43,25 @@ describe('launch remote', function () {
             }
         );
     });
+
+    it('closes target server at exit', async function () {
+        await dc?.hitBreakpoint(
+            fillDefaults(this.test, {
+                program: emptyProgram,
+                target: {
+                    // By default we use --once with gdbserver so that it naturally quits
+                    // when gdb disconnects. Here we leave that off and uses extended-remote
+                    // so that gdbserver doesn't quit automatically
+                    type: 'extended-remote',
+                    serverParameters: [':0', emptyProgram],
+                } as TargetLaunchArguments,
+            } as TargetLaunchRequestArguments),
+            {
+                path: emptySrc,
+                line: 3,
+            }
+        );
+
+        await dc?.stop();
+    });
 });
```

Jonah

2023-02-21 14:12 UTC, jonahgraham commented on src/GDBTargetDebugSession.ts
> +        while (!this.isReadyToStartGDBServer()) {
I think this should be in the disconnect method so that it is the disconnect request that fails if there is a problem terminating server rather than delaying that until the restart. 

This has two benefits:

1- Users who restart manually (by terminating one session and starting a new one) will benefit from the change
2- All uses of the disconnect will be testing the code, rather than waiting on restart to see the issue.

2023-02-22 17:16 UTC, QuocDoBV commented on src/GDBTargetDebugSession.ts
> +    protected async killProcess(pid: any): Promise<void> {
Honestly, It's the first time I work with subprocesses, I try some ways to kill GDB server. I use a command line to do that and it works as my expectation. I changed to subprocess to kill it.

2023-02-22 17:16 UTC, QuocDoBV commented on src/GDBTargetDebugSession.ts
> +    protected async isProcessRunning(pid: any): Promise<boolean> {
Like the above comment

2023-02-22 17:18 UTC, QuocDoBV commented on src/GDBTargetDebugSession.ts
> +                    : `ps -p ${pid}`;
I think it can work normally on macOS as my investigation. I have no environment to test on macOS, so I cannot confirm it.

2023-02-22 17:18 UTC, QuocDoBV commented on src/GDBTargetDebugSession.ts
> +                    : `kill -9 ${pid}`;
I think it can work normally on macOS as my investigation. I have no environment to test on macOS, so I cannot confirm it.

2023-02-22 17:30 UTC, QuocDoBV commented on src/GDBTargetDebugSession.ts
> +            this?.gdbserver?.on('exit', () => {
In the project that I'm working on, We have a problem when restart a debug session used emulator to debug. The problem is when we restart, GDB server cannot connect to emulator because the emulator still be hold by old GDB server. After trace cdt-gdb-adapter I found that disconnect and startGDBServer method run parallel(synchronize). So it cause the old GDB server is not still terminate but a new one started. So I set a flag is **this.isReadyToStartGDBServer()** to wait until GDB server is terminate completely then allow startGDBServer run. In disconnect method will send exit GDB command to exit GDB then wait then event "exit" to confirm GDB server has been exited successful then will set the flag to allow startGDBServer.

2023-02-22 17:36 UTC, QuocDoBV commented on src/GDBTargetDebugSession.ts
> +        while (!this.isReadyToStartGDBServer()) {
We need a flag to allow launch GDB method start after GDB server has been terminated.

2023-02-22 17:38 UTC, QuocDoBV commented
Hi @jonahgraham-san,
Could you help me review again?
About IT I will commit once the solution is accepted.

2023-02-22 18:04 UTC, jonahgraham commented on src/GDBTargetDebugSession.ts
> +        while (!this.isReadyToStartGDBServer()) {
Yes, but there are two places to wait for gdb server to be terminated, one is just before launching the next gdbserver (as you have done here) and the other is to wait when shutting down the session (in disconnectRequest). I think you should complete the full disconnect routine in the disconnect request.

2023-02-22 18:06 UTC, jonahgraham commented on src/GDBTargetDebugSession.ts
> +    protected async killProcess(pid: any): Promise<void> {
OK. ps/kill exist on mac normally AFAIK so this will be ok for now.

2023-02-22 18:10 UTC, jonahgraham commented on src/GDBTargetDebugSession.ts
> +    protected async killProcess(pid: any): Promise<void> {
> I changed to subprocess to kill it.

Did you? I expected to see a call to the kill method of the gdbserver (instead of gettings its pid). see docs https://nodejs.org/api/child_process.html#subprocesskillsignal

2023-02-22 18:11 UTC, jonahgraham commented on src/GDBTargetDebugSession.ts
> +                    : `kill -9 ${pid}`;
OK. ps/kill exist on mac normally AFAIK so this will be ok for now. But as you are investigating using subprocess.kill and exitcode you won't need to exec any processes at all hopefully.

2023-02-22 18:11 UTC, jonahgraham commented on src/GDBTargetDebugSession.ts
> +    static isGDBServerTerminated = true;
A reminder on this question.

2023-02-23 10:55 UTC, QuocDoBV commented on src/GDBTargetDebugSession.ts
> +    protected async killProcess(pid: any): Promise<void> {
Sorry for do not catch you idea. I updated it.

2023-02-23 10:56 UTC, QuocDoBV commented on src/GDBTargetDebugSession.ts
> +    protected async isProcessRunning(pid: any): Promise<boolean> {
I updated it.

2023-02-23 10:56 UTC, QuocDoBV commented on src/GDBTargetDebugSession.ts
> +            this?.gdbserver?.on('exit', () => {
I update it.

2023-02-23 11:02 UTC, QuocDoBV commented on src/GDBTargetDebugSession.ts
> +        while (!this.isReadyToStartGDBServer()) {
I updated it. If it does not match your idea, please help me know.

2023-02-23 13:33 UTC, QuocDoBV commented
Hi @jonahgraham,
Could you please help me review again?
Thank you!

2023-02-23 19:05 UTC, jonahgraham commented on src/GDBTargetDebugSession.ts
> +    static isGDBServerTerminated = true;
> When restart session, a new instance will be created. It means the instance of disconnectRequest() and startGDBServer() are different. So I have to use static to can share data between them.

I am quite confused now. If a new instance is created, doesn't that also mean that a new node process is created? Does your code work when running "normally" or only when running debug adapter in server mode?

2023-02-23 19:14 UTC, jonahgraham commented on src/GDBTargetDebugSession.ts
> +    static isGDBServerTerminated = true;
Also, it is probably time to add support for https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Terminate to make this code work best.

2023-02-23 19:16 UTC, jonahgraham commented on src/GDBTargetDebugSession.ts
> +        for (let i = 0; i < maxIterations; i++) {
This looks like a delay of worst case 7.5 seconds (15 * 500 / 1000). However VSCode will only [wait max 2 seconds](https://github.com/Microsoft/vscode/blob/e9229a18805fdb9baf7356ddc31bd216da5842ef/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L572) for disconnect to return.

2023-02-23 19:20 UTC, jonahgraham commented on src/GDBTargetDebugSession.ts
> +        for (let i = 0; i < maxIterations; i++) {
PS If you do implement terminate support, you sort of get 4 seconds from VSCode, 2 seconds to terminate and a further 2 seconds to disconnect.

2023-03-01 12:57 UTC, QuocDoBV commented
Hi @jonahgraham,
I have implemented terminate request in debug adapter and updated some code.
Could you please help me review it?
Thank you!

2023-03-01 13:08 UTC, QuocDoBV commented on src/GDBTargetDebugSession.ts
> +    static isGDBServerTerminated = true;
> I am quite confused now. If a new instance is created, doesn't that also mean that a new node process is created? Does your code work when running "normally" or only when running debug adapter in server mode?

It works normally when running not only for debug adapter in server mode. Do you have any idea instead of using static here?

2023-03-01 14:31 UTC, jonahgraham requested changes
@QuocDoBV I am sorry for these comments, but you have massively over-complicated this work. I have tried to guide you to simpler solution, but there seems to be some fundamental misunderstanding of what the life cycles are here. I recommend you look at https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/258 which will probably be merged soon and see if that change solves your problem.

I do apologize though, because my review comments have not helped work towards a better solution yet. I am not sure what I could have said, short of writing and testing the code myself, that could have guided you better on this journey. 

PS Please provide some tests.

2023-03-01 14:31 UTC, jonahgraham commented on src/GDBTargetDebugSession.ts
> +        while (!this.isReadyToStartGDBServer()) {
Delete this whole part of the change and do:

> I think you should complete the full disconnect routine in the disconnect request.

2023-03-01 14:31 UTC, jonahgraham commented on src/GDBTargetDebugSession.ts
> +    static isGDBServerTerminated = true;
For me I can see a new process is created when I restart the adapter. I simply can't see how this static can work. Please show me how the node cdt-gdb-adapter process is the same process before and after restart.

My guess is the code is working, but not for the reasons you think it is but simply because you initialize this static to true, so the place it is set to false is "lost" because the process changes.

2023-03-01 14:31 UTC, jonahgraham commented on src/GDBTargetDebugSession.ts
> +                    if (this.isProcessRunning()) {
I have no idea why you have a timeout here. All the methods you call in the timeout block are non-blocking. Please explain.

2023-03-01 15:08 UTC, QuocDoBV commented on src/GDBTargetDebugSession.ts
> +            await new Promise<void>((resolve) => {
To GDB server exits completely and emulator resets after GDB exits we need to wait some times. If we try to kill the gdb server immediately after sending "-gdb-exit" the emulator will be crash and need reset emulator to can connect in the next time. I check with the change in https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/258/files we cannot connect to debugger again if does not reset emulator. With Renesas  E2 emulator need about more 3s to gdb server can exit gracefully and leave emulator for the next connection complete. If not do so emulator will be hanged.

2023-03-01 15:10 UTC, QuocDoBV commented
Hi @jonahgraham-san,
Could you please help me confirm about my comment?
To GDB server exits completely and emulator resets after GDB exits we need to wait some times. If we try to kill the gdb server immediately after sending "-gdb-exit" the emulator will be crash and need reset emulator to can connect in the next time. I check with the change in https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/258/files we cannot connect to debugger again if does not reset emulator. With Renesas E2 emulator need about more 3s to gdb server can exit gracefully and leave emulator for the next connection complete. If not do so emulator will be hanged.

2023-03-01 15:26 UTC, jonahgraham commented on src/GDBTargetDebugSession.ts
> +            await new Promise<void>((resolve) => {
Does -gdb-exit cause the renesas gdb server to quit after a delay? If so, then what should be waited for is the `exit` signal of gdbserver process rather than a hard-coded 1.8seconds x 2.

2023-03-01 15:28 UTC, jonahgraham commented on src/GDBTargetDebugSession.ts
> +            await new Promise<void>((resolve) => {
To add to the complication, gdbserver.kill() on Linux only sends SIGTERM, on Windows it sends equivalent of SIGKILL.

2023-03-01 15:32 UTC, QuocDoBV commented on src/GDBTargetDebugSession.ts
> +            await new Promise<void>((resolve) => {
> Does -gdb-exit cause the renesas gdb server to quit after a delay? If so, then what should be waited for is the `exit` signal of gdbserver process rather than a hard-coded 1.8seconds x 2.

Yes It will quit after  more 3s. If I decrease less than 3s emulator will be hanged if try to kill GDB server.

2023-03-01 15:34 UTC, QuocDoBV commented on src/GDBTargetDebugSession.ts
> +            await new Promise<void>((resolve) => {
even it can only start debug again after disconnect session if reset emulator

2023-03-01 15:38 UTC, QuocDoBV commented on src/GDBTargetDebugSession.ts
> +            await new Promise<void>((resolve) => {
> 3 seconds is quite inconvenient as that is longer that the timeout in vscode, which is why you broke up the delay in two halves. I am not sure how to make that work, and it may require a change to vscode [here](https://github.com/Microsoft/vscode/blob/e9229a18805fdb9baf7356ddc31bd216da5842ef/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L572)
I will create a PR to VS code to request increase the time out. But should we make a work around to fix the problem first utill the PR is accepted?

2023-03-01 16:14 UTC, jonahgraham commented on src/GDBTargetDebugSession.ts
> +            await new Promise<void>((resolve) => {
I think we need both, so lets proceed.

Also, it sounds like the e2 gdbserver could be improved to not require 3 seconds to shutdown. So raising that as an issue too would be useful.

2023-03-22 18:24 UTC, jonahgraham commented
Solution replaced by #260

2023-03-22 18:24 UTC, closed without merging