Support Debug Console interacting directly with GDB
eclipse-cdt-cloud/cdt-gdb-adapter pull request #263
Opened 2023-04-25 10:08 UTC by trongle0504

This change adds the ability to interact with GDB directly in the debug console of VSCode by providing a way to bypass the normal expression evaluation and sending commands to the GDB console input.

To display the value of an expression, type that expression which can reference variables that are in scope. For example type `2 + 3` or the name of a variable. Arbitrary commands can be sent to GDB by prefixing the input with a `>`, for example type `>show version` or `>help`.

2023-04-25 10:12 UTC, trongle0504 commented
Hi @jonahgraham,
I have added some code to support sending GDB commands on CLI as your suggestion before.
Could you please help me review it?
Thank you!

2023-04-25 18:35 UTC, jonahgraham reviewed
Overall this LGTM. Please review test failures  Note until your first PR is approved I need to approve each run on the test suite in the PR, so please check the actions are successful in your own fork (https://github.com/trongle0504/cdt-gdb-adapter/actions)

2023-04-26 06:52 UTC, trongle0504 commented on src/GDBDebugSession.ts
> +                await mi.sendThreadSelectRequest(this.gdb, {
I updated it

2023-04-26 06:52 UTC, trongle0504 commented on src/integration-tests/evaluate.spec.ts
> +    it('should be able to update value of a variable which has local scope and named "monitor"', async function () {
I updated it

2023-04-26 06:54 UTC, trongle0504 commented
Hi @jonahgraham,
I have some updates as your suggestion.  The unit test also passed in my fork.
Could you please help me review it again?
Thank you!

2023-04-26 13:16 UTC, jonahgraham commented on src/GDBDebugSession.ts
> +                await mi.sendInterpreterExecConsole(this.gdb, {
I think you have misinterpreted the use of interpreter-exec console. Please see https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI-Miscellaneous-Commands.html#index-_002dinterpreter_002dexec and https://sourceware.org/gdb/onlinedocs/gdb/Context-management.html#Context-management

2023-04-26 13:18 UTC, jonahgraham commented on src/GDBDebugSession.ts
> +                await mi.sendInterpreterExecConsole(this.gdb, {
PS I don't know whether it is better to use interpreter-exec or not, I know that is how Eclipse CDT does it to though.

2023-04-27 09:24 UTC, trongle0504 commented on src/GDBDebugSession.ts
> +                await mi.sendInterpreterExecConsole(this.gdb, {
Hi @jonahgraham,
Thanks a lot for your documentation. I have some updates in the codes. I compared the currents response at CLI in VS code and e2studio that they are similar. Could you please take a look the changes? If there is anything that need to be updated, please let me know.

2023-04-27 18:20 UTC, jonahgraham requested changes
This is very close to right, please review my latest comments.

2023-04-27 23:26 UTC, trongle0504 commented on src/integration-tests/evaluate.spec.ts
> +            expression: '>-gdb-version',
> `repl` is for humans to use, so no need to support MI.

I just based on e2studio to implement in VS code. On e2studio, user also can use MI command while debugging . If we don't need to support for MI command, I will update it.

2023-04-28 00:15 UTC, trongle0504 commented on src/mi/interpreter.ts
> +        `-interpreter-exec console "thread ${params.threadId}" "frame ${params.frameId}" "${params.command}"`
Sorry if I misunderstood your idea. Do you mean it should be `-interpreter-exec console "${params.command}" --frame ${params.frameId} --thread ${params.threadId} ` ?. If it is right, It's seem that `--frame` and `-- thread ` are not accepted the interpreter. I got error when send the command `-interpreter-exec console help --frame 0 --thread 1`, the error is `Undefined command: "--frame".  Try "help".` In e2studio, --frame and --thread info also don't  need include in GDB command when sending 
![image](https://user-images.githubusercontent.com/104537989/235016503-b8d0ca18-23bb-4b1b-ade1-130ae20f0bd9.png)

2023-04-28 00:27 UTC, trongle0504 commented on src/integration-tests/evaluate.spec.ts
> +            expression: '>-gdb-version',
> Why enable this flow? For starters `-` isn't [the only way](https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI-Input-Syntax.html#GDB_002fMI-Input-Syntax) to type an MI command, e.g. `123-gdb-version` is also an MI command.

I just based on what e2studio implemented. You can take a look at below image.  For commands have "-" the interpreter will implicitly understand that is a MI command. Others cases will not be a MI command then it will add more `-interpreter-exec console` before send to GDB
![image](https://user-images.githubusercontent.com/104537989/235020455-b319e3a2-63d8-4cc9-9a71-936acc37f3b7.png)

2023-04-28 00:44 UTC, trongle0504 commented on src/integration-tests/evaluate.spec.ts
> +            expression: '>-gdb-version',
Currently, in e2studio the interpreter relies on the first character to determine whether the command from the user is cli-command or mi-command. If the first character is a flash (-) the interpreter will understand implicitly that is a MI command, otherwise it's cli-command. 
![image](https://user-images.githubusercontent.com/104537989/235026378-6f93ae59-a93d-451d-aaf1-92b1177fa413.png)

2023-04-28 00:53 UTC, trongle0504 commented on src/integration-tests/evaluate.spec.ts
> +            expression: '>-gdb-version',
> For starters `-` isn't [the only way](https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI-Input-Syntax.html#GDB_002fMI-Input-Syntax) to type an MI command, e.g. `123-gdb-version` is also an MI command.

`-gdb-version` also has the first character is a dash. So the interpreter will understand implicitly is a MI command.
![image](https://user-images.githubusercontent.com/104537989/235028930-ff89859d-a888-46bd-bc24-b36c308254cd.png)

2023-04-28 11:03 UTC, trongle0504 commented on src/mi/interpreter.ts
> +        `-interpreter-exec console "thread ${params.threadId}" "frame ${params.frameId}" "${params.command}"`
I have try to change the format command to `-interpreter-exec --thread ${params.threadId} --frame ${params.frameId} console "${params.command}` then it can work normally

2023-04-28 11:12 UTC, trongle0504 commented on src/integration-tests/evaluate.spec.ts
> +            expression: '>-gdb-version',
Could you please help me confirm whether we should support MI command on cdt-gdb-adapter?

2023-04-28 14:24 UTC, jonahgraham approved these changes
This looks good to go now.

I have added an additional commit 0afeb61d318516691002ad66e5d0a0fec1dc570d to show the user some help when they startup. Can you please confirm this looks ok:

![image](https://user-images.githubusercontent.com/679236/235174329-ef93f265-2c89-4c5b-9b01-4728915aecc5.png)

2023-04-28 14:24 UTC, jonahgraham commented on src/GDBDebugSession.ts
> +                if (args.expression[1] === '-') {
Please disregard the previous comment - too much reviewing java.

2023-04-28 14:37 UTC, jonahgraham commented
> I have added an additional commit [0afeb61](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/commit/0afeb61d318516691002ad66e5d0a0fec1dc570d) to show the user some help when they startup. Can you please confirm this looks ok:

I have split this out into #266

2023-04-28 16:59 UTC, trongle0504 commented
> > I have added an additional commit [0afeb61](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/commit/0afeb61d318516691002ad66e5d0a0fec1dc570d) to show the user some help when they startup. Can you please confirm this looks ok:
> 
> I have split this out into #266

I got it. I think that your changes are very helpful.

2023-04-28 18:27 UTC, merged

2023-04-28 18:27 UTC, jonahgraham commented
Thanks @trongle0504 for the new feature.