Adding the ability to configure serial port output to the debug console + resolve unhandled notify
eclipse-cdt-cloud/cdt-gdb-adapter pull request #271
Opened 2023-06-29 19:28 UTC by AdhamRagabMCHP

This PR introduces a set of parameters that allow us to configure a serial line in the adapter to print UART output from on-board/emulation debug to the debug console. These parameters include the TCP port to hook onto (for emulation programs outputting UART output), or the serial port on the host machine to capture UART output from. For the serial line, we also configure the baud rate, stop bits, handshaking method, etc.

The source code looks to take these parameters to then configure serial ports and sockets to read UART data and output it to the debug console. It will also set up necessary event handlers, and changes the log level in the non-verbose case to allow for "log" messages to be printed in a manner such that UART output isn't designated as a "warning".

Lastly, GDBDebugSession.ts features an addition to remove a warning about an "unhandled notify" for the cmd-param-changed notification.

2023-06-29 19:58 UTC, jonahgraham commented
Thanks @AdhamRagabMCHP this looks like an interesting new feature. Thank you for taking the time to create a PR.

I have done a preliminary review of the code and here are my first thoughts:

- Please separate unrelated changes (e.g. cmd-param-changed and logging changes) into their own PRs. If they are independent we can get the reviewed and merged quickly and that reduces the diff size of this PR making it faster to review too. There is an additional benefit, once your first PR gets merged then GitHub considers you trusted and will run the GitHub actions checks automatically, so getting a trivial PR approved and merged is a great way to start
- Some of the new fields have been introduced in the global scope. Can they be moved into the debug session (e.g. SerialPort and socket)?
- Can the new parameters be grouped into their own interface? e.g. uartSerialPort to handshakingMethod be placed in a new structure and add a field called uart to the existing structure(s). This will allow users in the launch.json to logically group related entries together. 
- Can you explain the reason to use the logger to get messages from serial to the user? I think it may be better to create `OutputEvent`s with a custom destination (such as `"uart"` perhaps? or maybe `"stdout"`)
- We are going to need some tests for this code so that it can be exercised properly and to ensure it does not regress in the future.

Feature wise this provides one way comms from target to IDE. Is there a plan on how to support bidirectional communications? Bidirectional comms are not a pre-requisite, but I want to understand what the future path may look like.

2023-06-29 20:43 UTC, AdhamRagabMCHP commented
Thanks for your prompt review! This is really refreshing to witness.

I'll try to address your comments one-by-one here, and of course the changes requested will be incoming:
1. Sure, I can do that. I think logically, separating the changes in GDBDebugSession.ts and GDBTargetDebugSession.ts makes sense - they are unrelated changes. Changing the logging level is directly related to how I wanted to print the serial output (by using logger.log as opposed to logger.warn) coming from a user's application.
2. The socket has an event handler for closing, so that can be moved. However, we need to declare the SerialPort globally so that we can attempt to close the port on a disconnect request.
3. Sure, I can do something like that.
4. We're using the CDT-GDB-VSCode/Adapter to debug user applications on-board and/or through an emulation platform. In our setup, we have three debugging flows:
 - On-host debugging - We use a separate plugin for this (we were working on this flow before needed to support debugging on-board and through an emulation platform, where we came across this extension that was very helpful in remote debugging). In this case, output from the program prints directly to the debug console.
 - On-board debugging - In our case, a lot of our user applications feature some sort of output printed on the UART, and so as to prevent users from having to open up an external screen/gtkterm/Putty window to view UART output, we found it helpful to print it within their IDE. In this flow, we would be needing to read UART output across a serial line, necessitating the use of the NodeJS serialport library.
 - Debugging through an emulation platform - If you have no CPU for an application developed to work on-board, we also have the option to debug an application on an emulation platform that mimics the CPU you are compiling for. In this case, the flow would work just like the on-board debugging flow, except that we would try to read off of a TCP port that the emulation platform redirects UART output to.
 We want to be able to switch between all 3 flows without having to change how we debug/how we view debug results drastically. In our case, that means that the way output is printed should be the same across all three (hence printing output to the debug console). Doing so also preserves UART output in the generated log file for the debug session, which can be helpful for users debugging an application where they may expect specific output/output in a specific order.
 5. Sure, I'll think about what test cases I can add
 6. I don't think there is a concrete plan on our end to support bidirectional communication. We don't really have a use case right now where we'd need bidirectional communication, although it would be an interesting exercise to think about.

2023-06-29 21:00 UTC, jonahgraham commented
> Thanks @jonahgraham for your prompt review! This is really refreshing to witness.

:) I try to be quick when possible, but sometimes it can be very slow. Anytime feel free to ping me!

> 2. The socket has an event handler for closing, so that can be moved. However, we need to declare the SerialPort globally so that we can attempt to close the port on a disconnect request.

Not sure I undertand why here - if serialport is a field in the session you should be able to access in disconnect in the same way that we do `await this.gdb.sendGDBExit();` on the next line.

> 4. We're using the CDT-GDB-VSCode/Adapter to debug user applications on-board and/or through an emulation platform. In our setup, we have three debugging flows [...]

The output appearing the debug console isn't an issue for me. I'm just not terribly fond of user data going through the logger. Using an OutputEvent will still deliver the output to the debug console without all the extra indirection. However if you have a use case where making it go through the logger is important to you I won't block the PR on that issue.

> 5. Sure, I'll think about what test cases I can add

Please let me know if you need insight or help on writing test cases for this. The serial port one may be difficult, especially on Windows, but having at least something that exercises the code is useful.

2023-06-29 21:11 UTC, AdhamRagabMCHP commented
Thank you for your comments!
On 2: I see what you mean now - sure, I'll do something like that.
On 4: I'll try to make use of an OutputEvent and see how that changes the look of the output - perhaps it does what we want all the same without having to go through the logger.
On 5: Thanks so much! Yes, it will be difficult, so I may ping you from time to time :)

2023-06-30 17:40 UTC, AdhamRagabMCHP commented
I forgot to mention this in the commit message, but the latest commit also feature a small fix to properly disconnect remote targets when exiting a GDB session.

2023-06-30 18:01 UTC, jonahgraham commented
> I forgot to mention this in the commit message, but the latest commit also features a small fix to properly disconnect remote targets when exiting a GDB session.

Can you do that in a different PR please. The disconnect sequence has been a fairly big talking point, both on here and with some of the other adopters so I want to ensure that change is very visible.

2023-06-30 18:03 UTC, AdhamRagabMCHP commented
> > I forgot to mention this in the commit message, but the latest commit also features a small fix to properly disconnect remote targets when exiting a GDB session.
> 
> Can you do that in a different PR please. The disconnect sequence has been a fairly big talking point, both on here and with some of the other adopters so I want to ensure that change is very visible.

Sure that can work....I'll do that now

2023-06-30 18:20 UTC, jonahgraham requested changes
This code looks good and nearly ready. Other than some small comments that I hope are clear enough and some test code I think this is ready and a great new feature for the adapter.

2023-06-30 18:20 UTC, jonahgraham commented on src/GDBTargetDebugSession.ts
> +            this.sendEvent(
This looks like debugging the debug adapter message. I assume it isn't related to this change? The extra messages are ok in general if you think they help you and your users, but I find this one a little terse to be useful.

2023-06-30 18:20 UTC, jonahgraham commented on src/GDBTargetDebugSession.ts
> +                            delimiter: "\n",
Should either of these items be parameters for the user? Often in UARTs `\r\n` is used a delimiter. Also, while UTF-8 is most often ok, i.e. don't know if we should support other types.

2023-06-30 18:34 UTC, AdhamRagabMCHP commented on src/GDBTargetDebugSession.ts
> +let SerialPort: serialport.SerialPort = new serialport.SerialPort({
Resolved.

2023-06-30 18:50 UTC, AdhamRagabMCHP commented on src/GDBTargetDebugSession.ts
> +            this.sendEvent(
Removed.

2023-06-30 18:51 UTC, AdhamRagabMCHP commented on src/GDBTargetDebugSession.ts
> +            if (this.targetType === "remote") {
https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/pull/273 - Moved to a new PR.

2023-06-30 18:53 UTC, AdhamRagabMCHP commented on src/GDBTargetDebugSession.ts
> +                         * This is a placeholder for the socket. We assign the correct socket
Addressed.

2023-06-30 19:00 UTC, jonahgraham commented on src/GDBTargetDebugSession.ts
> +            if (target.uart !== undefined) {
> Although you the starting point for you for this method (startGDBAndAttachToTarget) was very large and complex, I think having the uart creation split out is fairly logical place to split it.

I just reread this comment and am sad by the mess it is. I hope you understood what I meant, but here is a clearer version:

Although this method (startGDBAndAttachToTarget) was already very large and complex when you started adding to it, I think we should try not to have too much additional complication. Having the uart creation split out at this time is a logical place to do it.

2023-06-30 19:03 UTC, jonahgraham commented on src/GDBTargetDebugSession.ts
> +                            delimiter: "\n",
The biggest issue I tend to see with (my client Renesas) is that sometimes reading ShiftJIS (Japanese default) encoded data as UTF-8 causes corruption. If we are only interested in ASCII then UTF-8 should indeed be ok.

2023-06-30 19:08 UTC, AdhamRagabMCHP commented on src/GDBTargetDebugSession.ts
> +            if (target.uart !== undefined) {
No worries! I understood the initial comment :)

2023-07-05 15:21 UTC, jonahgraham commented
> On 5: Thanks so much! Yes, it will be difficult, so I may ping you from time to time :)

Any luck with how to test the code? I want to make sure that we don't spend an unreasonable time on this part of it.

2023-07-05 18:20 UTC, AdhamRagabMCHP commented
> > On 5: Thanks so much! Yes, it will be difficult, so I may ping you from time to time :)
> 
> Any luck with how to test the code? I want to make sure that we don't spend an unreasonable time on this part of it.

Hey! I'm still trying to write the test-code - we had a long weekend here, so I'm just getting back to it now. I'll keep you posted on the test code - I'll start off writing a testcase for the socket case.

2023-07-05 19:58 UTC, AdhamRagabMCHP commented
> > On 5: Thanks so much! Yes, it will be difficult, so I may ping you from time to time :)
> 
> Any luck with how to test the code? I want to make sure that we don't spend an unreasonable time on this part of it.

On this - what's your policy of including binaries as part of the test suite? I think the easiest option for me would be to recreate a simple emulator setup and go from there, but perhaps you'd like to avoid including the emulator binary as part of the testsuite, in which case I would have to keep exploring different options.

2023-07-06 00:35 UTC, jonahgraham commented
We can't have binaries checked in, but we can build additional binaries as part of the build.

2023-07-06 18:49 UTC, AdhamRagabMCHP commented
> We can't have binaries checked in, but we can build additional binaries as part of the build.

Understandable. I currently have a working testcase (I think) - it requires netcat, which is pre-installed by default on most, if not all, Linux distros but will need to be downloaded manually for Windows - what's the policy in that case? I believe there's instructions to build it from source, but it would still require something like Cygwin.

2023-07-06 19:13 UTC, AdhamRagabMCHP commented
@jonahgraham Just wanted to double-check that the way I wrote the test is valid - seems that it passes on both Windows and Linux.

2023-07-07 03:28 UTC, jonahgraham requested changes
This looks very promising and in the right direction. I have offered some feedback and I hope it is useful. 

I do try to maintain a high bar for making sure new code is at least somewhat tested. However as you are the one doing this work I would appreciate your feedback if you find that the overhead of writing the test for this code is disproportionate to the perceived value.

2023-07-07 03:28 UTC, jonahgraham commented on src/integration-tests/debugClient.ts
> +                }),
You don't need to `then` the `waitForOutputEvent` because `waitForOutputEvent` will already fail if an output event without that category/output comes through.
```suggestion
                }),
```

2023-07-07 03:31 UTC, jonahgraham commented
> Understandable. I currently have a working testcase (I think) - it requires netcat, which is pre-installed by default on most, if not all, Linux distros but will need to be downloaded manually for Windows - what's the policy in that case? I believe there's instructions to build it from source, but it would still require something like Cygwin.

I think if the most straightforward way to write the tests is to use netcat or any tool that is Linux specific, I would simply mark the tests as skip on Windows. Getting the code coverage on Linux would be great and will help ensure that a future code change doesn't break your new feature.

If we later find a regression or error that is Windows specific we may then want to write a test that covers that case.

I hope that helps!

2023-07-07 15:16 UTC, AdhamRagabMCHP commented on src/integration-tests/launchRemote.spec.ts
> +        dc.getSocketOutput(
> This code is missing an `await` here, so the tests aren't actually running (they may be running, but they end up running in the background and the results aren't captured).
> 
> Below is some information you may find useful to track down test results:
> 
> I can see this is in the GitHub actions output [(link to the part quoted below)](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/actions/runs/5479172154/jobs/9980650432?pr=271#step:8:99):
> 
> ```
>   launch remote
>       ✔ /defaults/can launch remote and hit a breakpoint: 1125ms
>       ✔ /defaults/can print a message to the debug console sent from a socket server: 0ms
> ```
> 
> A `0ms` runtime is the indication of a problem as it means that the test hasn't actually run long enough to start/stop a gdb + gdbserver pair.
> 
> The other thing you can do is look at the logs (as too briefly mentioned [here](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/blob/main/README.md#testing-on-github-actions)). For example [this is the link](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/suites/14115793439/artifacts/789958902) to the Ubuntu logs for the run in question. In it the tests are organized by folder, so the logs for this test are in "launch remote" - each test is run multiple times, which is the next level in the hierarchy, followed by logs for the individual tests.
> 
> For this test I can see `/launch remote/defaults/can print a message to the debug console sent from a socket server.log` for the default test arguments. In that test you can see the `disconnect` is being sent by the client (aka the test class) in the same millisecond as the log file is created.
> 
> The Windows version of that file doesn't exist in the zip file. My best guess is that is because the adapter doesn't even have time to start before the test is over (process creation time on Windows being much slower than Linux generally). The log files are written by the adapter, so if the adapter doesn't even start the log file doesn't exist.

That's what I suspected as well - thank you for this feedback! It seemed odd that it worked on Windows, so just wanted to confirm that it hadn't actually ran.

2023-07-07 15:19 UTC, AdhamRagabMCHP commented on src/integration-tests/launchRemote.spec.ts
> +                        "socketPort": "3456",
I missed this - thank you for the feedback. I was playing around with these ports while developing. I'll fix this in my next commit.

2023-07-07 15:19 UTC, AdhamRagabMCHP commented on src/integration-tests/debugClient.ts
> +                }),
Thank you! I'll apply this change.

2023-07-07 15:21 UTC, AdhamRagabMCHP commented
> > Understandable. I currently have a working testcase (I think) - it requires netcat, which is pre-installed by default on most, if not all, Linux distros but will need to be downloaded manually for Windows - what's the policy in that case? I believe there's instructions to build it from source, but it would still require something like Cygwin.
> 
> I think if the most straightforward way to write the tests is to use netcat or any tool that is Linux specific, I would simply mark the tests as skip on Windows. Getting the code coverage on Linux would be great and will help ensure that a future code change doesn't break your new feature.
> 
> If we later find a regression or error that is Windows specific we may then want to write a test that covers that case.
> 
> I hope that helps!

I think NodeJS hopefully is a way forward - other than the serial port (which we'll look into for now), I think there's probably some promise there. I want to avoid having to download any tools, so I'll keep looking.

Thank you so much for all your helpful feedback on this - I've learnt a lot!

2023-07-07 15:24 UTC, AdhamRagabMCHP commented on src/integration-tests/launchRemote.spec.ts
> +                initCommands: ["shell echo \"Hello World!\" | nc -l 3456 &"],
I was playing around with socat yesteday actually - it seems promising on Linux like you said, and just like you mentioned - the roadblock is a cross-platform solution. I've found that simulating a socket server from the terminal was probably my best solution, so the NodeJS way should hopefully work. I'll push a commit for this.

2023-07-07 18:41 UTC, AdhamRagabMCHP commented
@jonahgraham is there a way I can get access to the logfile from the most recent run, or does it get cleaned up after the tests run? I don' want to keep force pushing blindly - I can't run these tests locally so I'm relying on the PR run to test them.

2023-07-07 18:44 UTC, jonahgraham commented
> @jonahgraham is there a way I can get access to the logfile from the most recent run, or does it get cleaned up after the tests run?

Yes - they should all be there: https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/actions - the logs are preserved indefinitely.

> I don't want to keep force pushing blindly - I can't run these tests locally so I'm relying on the PR run to test them.

The other thing you can do is enable github actions on your fork and then all pushes you do will run the actions on your GHA: https://github.com/AdhamRagabMCHP/cdt-gdb-adapter/actions

2023-07-07 18:44 UTC, jonahgraham commented
Specifically the most recent run seems to be https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/actions/runs/5489485644

2023-07-07 18:56 UTC, AdhamRagabMCHP commented
> Specifically the most recent run seems to be https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/actions/runs/5489485644

I was referring more to the adapter log files - where we can see the verbose adapter logs. I haven't been able to find those logs at all.

2023-07-07 21:13 UTC, jonahgraham commented
Click on the run link, then Summary in the top left:

![image](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/assets/679236/1e8dc39d-6842-428a-90d3-a145e3ef17f4)

Then scroll down a little and download the zipped log files per platform:

![image](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/assets/679236/490b00f9-3416-4765-9c51-96eb1fbdf017)

2023-07-07 21:52 UTC, AdhamRagabMCHP commented
> Click on the run link, then Summary in the top left:
> 
> ![image](https://user-images.githubusercontent.com/679236/251862319-1e8dc39d-6842-428a-90d3-a145e3ef17f4.png)
> 
> Then scroll down a little and download the zipped log files per platform:
> 
> ![image](https://user-images.githubusercontent.com/679236/251862496-490b00f9-3416-4765-9c51-96eb1fbdf017.png)

Thank you so much!

2023-07-09 04:36 UTC, AdhamRagabMCHP commented
The socket test passes on both Ubuntu and Windows now - just formatting the source code now.

I'll look to add the test for the serial port.

2023-07-09 06:07 UTC, AdhamRagabMCHP commented
I added the test for the serial line output - I skip the test on Windows, and it passes in Linux.

2023-07-09 06:24 UTC, AdhamRagabMCHP commented
> I added the test for the serial line output - I skip the test on Windows, and it passes in Linux.

Actually - I noticed that sometimes, it fails to register as a success for this last one - from seeing the logs, it seems that the intended behaviour occurs and in fact, some of the runs show the test as having passed:

![image](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/assets/126698368/cdbabdd4-01c5-43d6-861a-54021e0fc0dd)


Is there anything I'm missing?

2023-07-10 15:40 UTC, jonahgraham requested changes
This is very close to done. Looks very good to me. Please see the individual comments for what is left.

2023-07-10 15:40 UTC, jonahgraham commented on src/integration-tests/debugClient.ts
> +        ]);
> Is there anything I'm missing?

The reason the tests are unstable is because you only start waiting for the output after launch returns - but if the output comes too quickly after the launch before you have a chance to start `waitForOutputEvent` the output you are looking for is missed. Therefore you have a race condition here.

Here is a suggested change. 

```suggestion
        return Promise.all([
            this.waitForEvent('initialized'),
            this.launch(launchArgs),
            this.waitForOutputEvent(category, output),
        ]);
```

2023-07-10 15:40 UTC, jonahgraham commented on package.json
> +    "@types/serialport": "8.0.2"
I think `@types/serialport` should be a dev dependency and both of these dependency changes should also appear in the `yarn.lock` file

2023-07-10 15:40 UTC, jonahgraham commented on src/integration-tests/launchRemote.spec.ts
> +            [`${path.join(testProgramsDir, 'socketServer.js')}`],
Can you run this code in the same process (and write it in typescript)? If it needs to be in another process, you need to ensure the process is terminated as part of the test.

See also #277 - we don't want to make this problem worse :)

2023-07-10 15:40 UTC, jonahgraham commented on src/integration-tests/launchRemote.spec.ts
> +        cp.spawn('socat', [
You need to terminate `socat` - see [this](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/actions/runs/5498351729/jobs/10043412201#step:23:1):

![image](https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/assets/679236/422e7b1e-fdd3-4150-8bf2-c43fd3015f88)

2023-07-10 16:32 UTC, AdhamRagabMCHP commented on src/integration-tests/launchRemote.spec.ts
> +            [`${path.join(testProgramsDir, 'socketServer.js')}`],
Resolved - I'll ensure the process is terminated as part of the test.

2023-07-10 16:32 UTC, AdhamRagabMCHP commented on src/integration-tests/launchRemote.spec.ts
> +        cp.spawn('socat', [
Resolved - I'll ensure the process is terminated as part of the test.

2023-07-10 16:41 UTC, AdhamRagabMCHP commented on src/integration-tests/launchRemote.spec.ts
> +            [`${path.join(testProgramsDir, 'socketServer.js')}`],
https://github.com/eclipse-cdt-cloud/cdt-gdb-adapter/actions/runs/5510587354/jobs/10045008025#step:23:1 - All processes are terminated.

2023-07-10 16:50 UTC, AdhamRagabMCHP commented on package.json
> +    "@types/serialport": "8.0.2"
Resolved.

2023-07-10 17:11 UTC, jonahgraham commented
@AdhamRagabMCHP it looks like you have resolved all my outstanding review comments. Please let me know if you have anything else pending or if you are ready for me to merge.

2023-07-10 17:12 UTC, AdhamRagab25 commented
I think it's good to merge - I don't think I'll be adding anything else to the PR.

2023-07-10 17:15 UTC, jonahgraham approved these changes

2023-07-10 17:18 UTC, merged

2023-07-10 17:19 UTC, jonahgraham commented
Thank you @AdhamRagab25 for this new functionality!

2023-07-10 18:02 UTC, AdhamRagabMCHP commented
@jonahgraham Thank you for all your help and feedback! It was incredibly helpful!