Wait for pause
eclipse-cdt-cloud/cdt-gdb-adapter pull request #339
Opened 2024-11-07 19:27 UTC by Luke-zhang-mchp

Closes #295.

Code to suspend/continue the debug session when setting breakpoints are moved to a reusable function `pause` and `continue` methods. The `pause` method `await`s a promise which gets resolves when the target is actually suspended.

This `pause` method is also used in `GDBTargetDebugSession::disconnectRequest`.

2024-11-07 19:30 UTC, Luke-zhang-mchp commented
Hey @jonahgraham, this is what I assume the issue was alluding to, and it works fine on our IDE. Let me know how the changes look.

2024-11-07 19:39 UTC, Luke-zhang-mchp commented on src/gdb/GDBDebugSessionBase.ts
> +    protected async pause(): Promise<void> {
I think this name is questionable, since there's also `pauseRequest` and `continueRequest`, but I'm not sure what a good name would be. Something like `pauseAndWait`?

2024-11-08 00:30 UTC, jonahgraham reviewed
This looks quite close to what I was talking about - but I was hoping the logic for "waitPauseNeeded" could be in the new method.

i.e. have a single call that is "pauseIfNeeded" that can be awaited, and then at the end of the block "resumeIfNeeded" that is perhaps passed a token pauseIfNeeded returned (or elsewhere stored in the state).

---
sort of related topic brain dump:

This is a place I really like Python's `with` statement, because in Python I would write something like:

```python
    with this.targetPaused():
        // do some operations on a paused target
```

which will pause if needed at the beginning and resume automatically when leaving the block.

2024-11-08 20:42 UTC, Luke-zhang-mchp commented
Yeah that with statement would be really nice. What about [method decorators](https://www.typescriptlang.org/docs/handbook/decorators.html#method-decorators)? It's not really the same cause it would be the beginning and end of the function. Also probably not worth the trouble, but it would be something like:

```ts
const paused = <T extends []>(
    target: GDBDebugSessionBase,
    propertyKey: string,
    descriptor: TypedPropertyDescriptor<(...args: T[]) => void>
) => {
    const originalMethod = descriptor.value; // Original function

    descriptor.value = function (...args: T[]) {
        target.pause();
        originalMethod?.apply(this, args);
        target.continue();
    };
};

export abstract class GDBDebugSessionBase extends LoggingDebugSession {
    @paused
    protected async setBreakPointsRequest(
        response: DebugProtocol.SetBreakpointsResponse,
        args: DebugProtocol.SetBreakpointsArguments
    ): Promise<void> {}
}
```

2024-11-11 15:25 UTC, jonahgraham commented
> What about [method decorators](https://www.typescriptlang.org/docs/handbook/decorators.html#method-decorators)?

My lack of experience with typescript means I don't know if this is a good idea or not in this case. 

> Also probably not worth the trouble

That is my instinct for now.

2024-11-11 15:55 UTC, jonahgraham reviewed
This change looks correct - but it also looks like it exposes some issues in the tests when async is off.

For example I can see in `logpoints/remote gdb-async-off/hits a logpoint.log` that at the moment that the SIGINT is sent to gdb, inferior happens to be paused, leading to this output:

```
[21:00:09.996 UTC] GDB signal: SIGINT to pid 13380
[21:00:09.996 UTC] GDB notify async: breakpoint-modified,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",addr="0x000055555555513f",func="main",file="count.c",fullname="/home/runner/work/cdt-gdb-adapter/cdt-gdb-adapter/src/integration-tests/test-programs/count.c",line="4",thread-groups=["i1"],times="2",original-location="-source /home/runner/work/cdt-gdb-adapter/cdt-gdb-adapter/src/integration-tests/test-programs/count.c -line 4"}
[21:00:09.996 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"log","output":"Quit\n"}}
```

What this means is that the adapter thought the inferior was running, so sent a SIGINT, but in the time between the test and SIGINT being delivered, the inferior hit a breakpoint, so the SIGINT was interpreted as Quit instead of pause.

This is a fundamental problem with async mode because this race condition can not be detected or avoided.  What I don't know is if/why this change exposes this problem more, or if it was just bad luck. I have restarted the tests in the first instance.

With async on by default for the last couple of years I don't think this matters too much. But we do need to have  a clean run. If the above isn't enough information to resolve the issue, let me know and I can try to fix up these problematic test cases.

2024-11-12 00:06 UTC, jonahgraham requested changes

2024-11-12 00:06 UTC, jonahgraham commented on src/web/GDBTargetDebugSession.ts
> +                // Need to pause first, then disconnect and exit
The test failures in async mode are due to this change which expose the tests to the previously mentioned race condition more easily. For example continues.spec.ts runs code that hits a breakpoint in a tight loop, so in async mode the `disconnect` will be processed after hitting the next breakpoint without this change.

With this change a SIGINT is sent.

I think this is a test problem in async code and should be fixed in the tests rather than changing the code.

Let me know if you understand enough of what I have said to change the tests, if not I will fix the tests and we can rebase this change.

2024-11-12 00:50 UTC, Luke-zhang-04 commented on src/web/GDBTargetDebugSession.ts
> +                // Need to pause first, then disconnect and exit
Oh sorry, just saw this. I did get it working with the commit I just pushed (https://github.com/Luke-zhang-mchp/cdt-gdb-adapter/actions/runs/11788461303), but I will look at fixing the tests instead.

2024-11-12 01:02 UTC, jonahgraham commented on src/web/GDBTargetDebugSession.ts
> +                // Need to pause first, then disconnect and exit
The commit you just pushed maintains the status quo of having the same disconnect bug (in sync mode). We can just go with that for now and fix the disconnect bug in sync mode (or more likely leave it documented as known issue in a mode we don't recommend anyway)

PS. The last commit was pushed as a different author email, can you force push a new commit fixing the author please:

![image](https://github.com/user-attachments/assets/c9a2de09-557e-4739-be4a-9e314d68aeff)

2024-11-12 01:18 UTC, Luke-zhang-04 commented on src/web/GDBTargetDebugSession.ts
> +                // Need to pause first, then disconnect and exit
Ah shoot, I didn't think that would be much of an issue, I don't have my work laptop with me. I'll take a closer look tomorrow and see if I can fix it in the tests.

2024-11-13 15:13 UTC, jonahgraham commented on src/web/GDBTargetDebugSession.ts
> +                // Need to pause first, then disconnect and exit
> Just to make sure, you meant to say sync mode right? It seems to make more sense that way.

Not sure which line ^^^ was in response to, so....

> The commit you just pushed maintains the status quo of having the same disconnect bug (in sync mode). We can just go with that for now and fix the disconnect bug in sync mode (or more likely leave it documented as known issue in a mode we don't recommend anyway)

... I'll rephrase ^^^ because it wasn't super clear

The change you have added with `requireAsync = false` parameter added to `pauseIfNeeded` is acceptable for now. It means that in sync mode `disconnectRequest` doesn't work reliably, but that is ok as that is the status quo.

I would like API to not recommend that `requireAsync` be used at all and that it will be removed in the future. We can state that `pauseIfNeeded` and `disconnectRequest` don't work reliably in sync mode and recommend users (extenders really) only use async mode.

If someone has a need for reliable sync mode, then they can contribute fixes/improvements.

2024-11-14 00:23 UTC, Luke-zhang-mchp commented on src/web/GDBTargetDebugSession.ts
> +                // Need to pause first, then disconnect and exit
Ok so I just spent the day trying to fix the tests as you suggested earlier and... I think it's time for me to give up. The multithread one is particularly annoying to debug, since it's only an issue every 1 in 20 runs on my machine. I did manage to fix the logpoint failure consistently (312d977d06c4305e9007fd166b9162e491d985d3). I think the last straw was when the test from `continues` failed (https://github.com/Luke-zhang-mchp/cdt-gdb-adapter/actions/runs/11826261580/job/32951836487#step:8:1024), and I realized that the issues in sync mode are probably deeper than I had thought.

Just for the record, here are all the changes I ended up making: https://github.com/Luke-zhang-mchp/cdt-gdb-adapter/compare/8b3628ec62e1e3cf851fc189b5f5db4cdae4f643...Luke-zhang-mchp:cdt-gdb-adapter:61e9ff046c09528c5b8020acf8eca0475ef7b5de.

I'll make the changes for recommending against `requireAsync` in the form of deprecated overloads.

2024-11-14 00:44 UTC, Luke-zhang-mchp commented on src/web/GDBTargetDebugSession.ts
> +                // Need to pause first, then disconnect and exit
I added warning comments, but they don't do a great job at warning about sync mode specifically. Are you also looking for runtime warnings?

2024-11-14 01:38 UTC, jonahgraham approved these changes

2024-11-14 01:38 UTC, jonahgraham commented on src/web/GDBTargetDebugSession.ts
> +                // Need to pause first, then disconnect and exit
What you have done here is what I had hoped for. Thanks for spending time looking at the other tests, it is great to have more people familiar with how all this works to be able to maintain this long term.

Thanks @Luke-zhang-mchp - I am going to merge this version of the change.

2024-11-14 01:40 UTC, merged